### ISSUE TITLE
Activating anything in the "Other" category, freezes the game.

### ISSUE THREAD

**Issue by NumberXer0** [joffnerd/botw-trainer#1]
Rupees, Stamina and Health. Once you press save, causes a full lock up and forced reset of the entire console. Version US 1.1.

**Comment by Crashdummyy** [comment]
Debug Log ?

**Comment by joffnerd** [comment]
I'm on PAL. It may not work for US. I need the info for that Tab for US

**Comment by joffnerd** [comment]
Should be fixed now.
