### ISSUE TITLE
Key items getting maxed unexpectedly?

### ISSUE THREAD

**Issue by Ailuros** [joffnerd/botw-trainer#10]
While messing with the Rupees and Health values on the Codes tab, myself and one other person have had strange things happen, seemingly at random. It's the same every time. At times, checking the checkbox (or unchecking it) next to Rupees or Health and clicking save causes the last 5 or so items on my food tab in the game (all the stackable ones) to go up to a quantity of 2500, and all my key items to go to 2500 (or after a save and load, 999). I'm trying to pin down exactly what causes it. If I can reliably reproduce it, I'll be sure to detail how here. I'm also going to look in the debug to see if other food items are being changed, just not visibly. Still, I'm pretty sure this has something to do with the rupees or health on the code tab, as I've never run into this strange behavior when just using the trainer to edit weapon durability or give myself infinite stamina.

**Comment by joffnerd** [comment]
Its probably because you didn't refresh before saving

Items move around in memory, if you pick things up and get new stuff but don't refresh you are going to be overwriting items

**Comment by Ailuros** [comment]
Ah. I'll test that then.

**Comment by Ailuros** [comment]
Yes, it seems if I refresh before using codes that this behavior doesn't happen. At least, it hasn't happened again thus far. Also, it seems like 2.0 refreshes much faster, so I don't see this being a problem in the future. Thank you!
