### ISSUE TITLE
new idea for a code!

### ISSUE THREAD

**Issue by fefe7198** [joffnerd/botw-trainer#100]
how about a blood moon code to respawn everything in the map? (mostly waiting for that apple tree puzzle for korok and idk how to trigger blood moons easily xD)

**Comment by xNeptune** [comment]
Lol, I admire the thought, I've been looking around for a way to trigger this also, I'll see what I can come up with and I should be able to make a pull request on the trainer to get it added in 👍

**Comment by fefe7198** [comment]
dang. what a fast reply xD also thanks!
