### ISSUE TITLE
Yo! i found a way to make a glitch blood moon spawn

### ISSUE THREAD

**Issue by fefe7198** [joffnerd/botw-trainer#101]
basiacly you go to gerudo tower using the teleport code. u use the slow motion arrow thingie and then teleport to great plateu tower. it should spawn a blood moon but glitched at any time xD (if it dosent try again also. u will die if u dont have fairies or mipha's grace)

**Comment by joffnerd** [comment]
Post about this on the GBA forums, this is for issues. Thanks

**Comment by JellyBelly12346** [comment]
When I use page feature it deletes all of my items in game.
