### ISSUE TITLE
After 3.8.1 came out i been having problems 

### ISSUE THREAD

**Issue by chariram123** [joffnerd/botw-trainer#103]
my problems is: my keeps saying Connection closed. 
at BotwTrainer.TcpConn.Read(Byte[] buffer, UInt32 nobytes, UInt32& bytesRead)
at BotwTrainer.Gecko.ReadDataBufferSize()
at BotwTrainer.Gecko..ctor(TcpConn tcpConn, MainWindow mainWindow)
at BotwTrainer.MainWindow.ConnectClick(Object sender, RoutedEventArgs e)

how can i fix this? my internet works good on both my wii u and my laptop . i tried it at my step mon's house ( when i first got 3.8.1 ) it worked fine but ones i got to my mom's it won't work.

**Comment by xNeptune** [comment]
your wii u IP is different at both locations, you need to find the correct IP address again

**Comment by chariram123** [comment]
it was the correct ip it worked like a second ago and then it didn't when i tryed it again. it dose this on and off

**Comment by xNeptune** [comment]
Do you possibly have a static IP address to your knowledge? or a router that refreshes your IP after a certain duration?

**Comment by Slade1972** [comment]
I'm having the same issue with 3.8.2 after updating to V1.1.1.

> Connection closed.   at BotwTrainer.TcpConn.Read(Byte[] buffer, UInt32 nobytes, UInt32& bytesRead)
>   at BotwTrainer.Gecko.ReadDataBufferSize()
>   at BotwTrainer.Gecko..ctor(TcpConn tcpConn, MainWindow mainWindow)
>   at BotwTrainer.MainWindow.ConnectClick(Object sender, RoutedEventArgs e)

Static IP via my ISP, WiiU's IP has been confirmed as correct, and with no other changes to either system. V3.4 worked yesterday prior to updating, and I haven't restarted my computer since.

I will try updating the Gecko U files and see if that makes a difference.
