### ISSUE TITLE
DSI occurred and game crashs

### ISSUE THREAD

**Issue by game954** [joffnerd/botw-trainer#107]
I've done these steps 
1,Go to Homebrew
2, Open TCP Gecko on the Wii U
3, Press X to start Gecko with CosmoCortney's CodeHandler
4, Start Legend of Zelda: Breath of The Wild
5, Open the Trainer on your PC and Connect to your Wii U using its IP 

After I Connect my Wii U IP the games crash, I have everything on my SD card set up rite and updated. Is my widows 10 bucking the trainer? how can I fix this?

**Comment by EclipseSin** [comment]
Make sure you are loaded into the game (continue or after the intro scene on a new game) first before connecting with the trainer. Also be sure to be using the latest version of the game.

**Comment by game954** [comment]
I did load into my game save but trainer still crashed after I connected. So how do I the latest version of the game? I block Nintendo from siding updates just incase they try to patch my hacking games. I'm still connected to my internet on Wii U. Is there a way resave updates to Zelda botw game without Nintendo?

**Comment by xNeptune** [comment]
When you're at the start screen for the game look to the bottom right corner of the screen and you should see a version number there. What is it?

**Comment by EclipseSin** [comment]
If you need to update without removing your DNS settings, use your computer and a software such as nusgrabber or Wii U Usb Helper to get update v48, which is v1.1.1 on the bottom right corner of the start screen as xNeptune has advised. You can then install the update to the same device as the game using wup installer y mod or others.

**Comment by game954** [comment]
Thank to both of you now I know what I'm doing worng
