### ISSUE TITLE
Request - New Update Link

### ISSUE THREAD

**Issue by KitBallard64** [joffnerd/botw-trainer#109]
Thanks for continuing work on this. Was wondering if you could add a button that directs the web browser to your newest update? Be faster than hitting "Ok" then having to go through a few extra steps to find the newest update. If not, that's cool XD

**Comment by xNeptune** [comment]
I'll see if I can get on this today and make a pull request for the trainer.

**Comment by joffnerd** [comment]
Don't worry, I have  coded this already and  will be part of next release.

Ta
