### ISSUE TITLE
Item change not working?

### ISSUE THREAD

**Issue by RowanFN** [joffnerd/botw-trainer#11]
Hey,
Saw you can change item names etc,
I've looked into which item I'm after (this case the light bow) and o change the item name, save....nothing happens, I also change the item value and save/load... Nothing

I've also tried seeing to change some armour pieces but everything remains the same

**Comment by joffnerd** [comment]
what is the weapon name of the light bow?

**Comment by Darrick255** [comment]
TheRevolution1 posted posted a bunch of item information at https://gbatemp.net/threads/post-your-wiiu-cheat-codes-here.395443/page-301 you can look at the names there.

071 = Bow of Light
072 = Twilight Bow

I hope that helps

**Comment by joffnerd** [comment]
I just changed my first bow Item Name to Weapon_Bow_071 and clicked save, opened my inventory and had it so working here.

**Comment by septemus** [comment]
It could be the difference between US + EU versions. Item changing wasn't working for me either, so I used JGecko to browse to the address listed with your trainer for the name and changed it there. I can send a screenshot of the difference when I get home if that would help.

**Comment by joffnerd** [comment]
Yeah I count vouch for US im afraid. Seems to work for some and not others

**Comment by RowanFN** [comment]
I got it working after updating a few versions of this, mist of been that version for eur
