### ISSUE TITLE
1.1.1 Code's stopped working

### ISSUE THREAD

**Issue by wazzusig** [joffnerd/botw-trainer#110]
I have not updated to 1.1.2 for fear the program will stop working altogether. 

The codes for moon jump, and speed modifier work on 3.8.3, but not on 3.8.2, 3.8.4, or 3.8.5 for me.

Also, will 1.1.2 break the trainer?

Thanks!

**Comment by fefe7198** [comment]
i have tested and most codes are still working (expect the immune codes and some teleport codes) in 1.1.2 ....well at least on my game they work xD

**Comment by wazzusig** [comment]
Thanks, I don't really use those codes, so maybe I'll update. Any improvements in BOTW are welcome IMO

**Comment by fefe7198** [comment]
hey your welcome xD

**Comment by wazzusig** [comment]
What version of the BOTW Trainer are you using and does moon jump and speed modifier work for you on 1.1.2 with your version or the Trainer?

**Comment by fefe7198** [comment]
they both work fine. just the teleport codes. (oh yeah. the time update also does not work)

**Comment by wazzusig** [comment]
Perhaps the fault is that I am testing this wrong. I am using 3.8.3 (working) on my PC, tested 3.8.4, 3.8.5, 3.8.2 on my laptop (running back and forth from pc to tv is not ideal, lol). While I'm adding a variable, I find it curious that the laptop would be the issue when all other aspects of the trainer (that I've tried anyway) work, just not the speed modifier and the moon jump.

**Comment by fefe7198** [comment]
huh thats weird....

**Comment by thedarkparadox** [comment]
Will go ahead and add my $0.02. Using v3.8.5 on 1.1.2. Nothing is working. Able to get connected and nothing in the Error Log, but absolutely nothing is working. Tried saving and loading a couple of times as well. No changes to my inventory, rupees, etc. Just as I get all this working is when the update rolls out, too. Hopefully there will be a patch soon to this trainer. Really appreciate the work that was done and the UI. Looking forward to using it. Cheers.

**Comment by wazzusig** [comment]
I feel stupid....I didn't have the gamepad selected. It made the difference on my laptop. Still haven't updated to 1.1.2.
