### ISSUE TITLE
Trainer Refusing to load all items

### ISSUE THREAD

**Issue by InkDragon** [joffnerd/botw-trainer#111]
This is for version 3.8.6
I'll go to refresh the item list after cooking and it'll say something like 262 items found
but it'll only load 259 of those items and anything I cooked since the last refresh won't show.

Sometimes saving and reloading the game will fix it.
Sometimes disconnecting and reconnecting will fix it.
Other times I have to completely close the trainer, and it still wont read all the items.

This is a problem that just started happening in this latest version. Previous versions I had zero issues with loading the item list.

**Comment by joffnerd** [comment]
Try 3.8.7

**Comment by InkDragon** [comment]
Issue seems to be fixed now, thank you
