### ISSUE TITLE
Infinite Stamina Issue

### ISSUE THREAD

**Issue by XenocodeRCE** [joffnerd/botw-trainer#114]
Error : Infinite stamina / stamina value editing doesn't seems to have any effect on the game.
No Error log.

**Comment by XenocodeRCE** [comment]
actually none of the Codes tab works

**Comment by joffnerd** [comment]
You aren't using the correct tcpgecko if that's the case. Check the readme

**Comment by joffnerd** [comment]
Also, double check your .Net version

**Comment by XenocodeRCE** [comment]
1. I am using the correct tcpgecko elf file
2. I have the correct .NET Framework version

**Comment by xNeptune** [comment]
your IP address could be wrong
Are you able to load items within the trainer? Or are you just hitting connect and using the yellow tabs?

**Comment by XenocodeRCE** [comment]
I'm indeed able to swap item, everything seems to be working except Codes tab

**Comment by joffnerd** [comment]
What version of the game are you on?

**Comment by XenocodeRCE** [comment]
Latest update v64

**Comment by joffnerd** [comment]
Weird, if you have the correct tcp files, .net version and game version then I don't know i'm afraid. You are clicking save at the bottom right?

Can you record a video?

**Comment by XenocodeRCE** [comment]
I can't record a video since i'm using the wii u version of BOTW and therefore i would need to use my phone to record. No offense but i don't think i'm retarded.

http://i.imgur.com/rcoQlJh.png the codes tab page after  clicked save, 
http://i.imgur.com/4bIz5TU.jpg but in game i have the same amount of rupee

**Comment by joffnerd** [comment]
Rupees will only change when you use them i think

**Comment by joffnerd** [comment]
If you want rupees just give yourself 100 diamonds then sell them

**Comment by XenocodeRCE** [comment]
i know right ? look at upper reply, there are tons of way to make rupee. I only want stamina

**Comment by joffnerd** [comment]
Oh, why did you post and comment on the rupees?

I honestly don't know why it doesn't work for you., You are the only person so far who is having a problem after checking gecko, .net and the game version.

When you start tcp gecko and press X does the black screen have your IP address?

**Comment by XenocodeRCE** [comment]
there is no ip on tcpgecko, i donloaded this java progra o the repo you lined, it has downloaded latest file, i put it on sdcard, i install tcpgecko w/ codehandler ad then i start botw 

imgur.com/gallery/jUEhT

**Comment by joffnerd** [comment]
What happens if you press the  test button on the trainer after connecting? Bottom right

The latest tcp gecko bully made shows your ip address so you don't seem to have the latest one

https://github.com/BullyWiiPlaza/tcpgecko

**Comment by XenocodeRCE** [comment]
http://i.imgur.com/gHKQVVY.png

**Comment by joffnerd** [comment]
[tcpgecko.zip](https://github.com/joffnerd/botw-trainer/files/930518/tcpgecko.zip)

Here are the files from my tcpgecko folder on my sd  card

**Comment by joffnerd** [comment]
Working now? If so i will close.
