### ISSUE TITLE
Cant connect to the trainer

### ISSUE THREAD

**Issue by bigdjill** [joffnerd/botw-trainer#117]
Hi. I'm having an issue connecting to the trainer. Im am using the latest tcpgecko files. I can connect to Jgecko U just fine. that's how i got my ip address but when i try the trainer I get these errors
 
1st time
Connection closed.   at BotwTrainer.TcpConn.Read(Byte[] buffer, UInt32 nobytes, UInt32& bytesRead)
   at BotwTrainer.Gecko.ReadDataBufferSize()
   at BotwTrainer.Gecko..ctor(TcpConn tcpConn, MainWindow mainWindow)
   at BotwTrainer.MainWindow.ConnectClick(Object sender, RoutedEventArgs e)

2nd time
Connection closed.   at BotwTrainer.TcpConn.Read(Byte[] buffer, UInt32 nobytes, UInt32& bytesRead)
   at BotwTrainer.Gecko.GetServerStatus()
   at BotwTrainer.MainWindow.ConnectClick(Object sender, RoutedEventArgs e)

**Comment by joffnerd** [comment]
Does your tcp gecko look like this when you run it

https://joffnerd.s3.amazonaws.com/tcpgecko.jpg

Also,  double check your .net version is 4.6.2. Installer linked in the readme

**Comment by bigdjill** [comment]
Yes. I do have the ip at the top of my screen and I do have the latest version of .net installed.

**Comment by bigdjill** [comment]
https://drive.google.com/file/d/0By2jh7K7-MfMUE43WHZUZmcxNXM/view?usp=sharing

**Comment by joffnerd** [comment]
Yeah that's odd, just stating the obvious but you can't connect to both at the same time.

**Comment by bigdjill** [comment]
No

**Comment by joffnerd** [comment]
What happens if you uncheck the box next to connect?

**Comment by bigdjill** [comment]
hey i got it connected. I can't be connected to both of them at the same time. this can be closed. thanks for the help.
