### ISSUE TITLE
Somewhat frequent crashing

### ISSUE THREAD

**Issue by crymsoncristal** [joffnerd/botw-trainer#119]
The trainer works perfectly except for the random crashes. They happen anywhere between 30 minutes to a few hours after starting the game. I just wanted to know if I'm doing something wrong or if you could possibly fix the issue.

**Comment by xNeptune** [comment]
Any idea what you're doing when these crashes occur? And is it solely the trainer that crashes or is it the game also?

**Comment by crymsoncristal** [comment]
The game itself has never crashed when I wasn't using the trainer. However, since the most recent update, I haven't had a crash, so the issue may very well have been inadvertently resolved.

**Comment by 0100100001001001** [comment]
Happens with me too.  With either multiplier code ( speed / damage ).  I don't think its anything to do with the trainer, I think it has to do with memory getting corrupted in the game.  Just save often, and be thankful for the  autosave.

**Comment by GoodP** [comment]
Maybe your game must not be updated. Latest trainer needs to be with zelda botw's latest update.

**Comment by joffnerd** [comment]
The game crashes anyway, i think it pushes the Wii U a bit too far in terms of coping.

**Comment by Ailuros** [comment]
Indeed. I had all the Divine Beast codes, the durability codes, stealth, and the immunity code on, which shouldn't be that demanding, and warped to Shae Mo'sah Shrine, then started paragliding north over the volcano, and in one area near the north mine where the particle effects were particular heavy and enemies were shooting at me it froze. And most of the framerate issues I've  ever had were when enemies and myself were using weapons with fancy visual effects like Ice Arrows. One framerate drop was so bad I thought my game had frozen for about a half second before it began chugging along again. I think the game just taxes the system.
