### ISSUE TITLE
connect error

### ISSUE THREAD

**Issue by moedope** [joffnerd/botw-trainer#120]
it was working fine but now it gives me this error
I even deleted all from sd card and did all from scratch but no go
error
Error data will appear here
Connection closed.   at BotwTrainer.TcpConn.Read(Byte[] buffer, UInt32 nobytes, UInt32& bytesRead)
   at BotwTrainer.Gecko.ReadDataBufferSize()
   at BotwTrainer.Gecko..ctor(TcpConn tcpConn, MainWindow mainWindow)
   at BotwTrainer.MainWindow.ConnectClick(Object sender, RoutedEventArgs e)

**Comment by xNeptune** [comment]
Are you sure you have the correct IP address? They can change from time to time depending on your network situation.

**Comment by moedope** [comment]
Yes ive set static ip and even ping tested it

**Comment by moedope** [comment]
If i uncheck read buffer size the game frezzes

**Comment by xNeptune** [comment]
If you uncheck it during playing?
I'd just suggest not changing that option until you disconnect
