### ISSUE TITLE
How to summon WolfLink and Epona! PLS!!

### ISSUE THREAD

**Issue by GoodP** [joffnerd/botw-trainer#124]
I ask because I've search the internet but I found nothing good. There are a lot of codes listed but there are no tutorials on how to do it. That's why I ask here! Then leading me back from what I already did. If you have details explanation on how to summon them, than thanks much appreciated. I hope so.

**Comment by joffnerd** [comment]
https://gbatemp.net/threads/post-your-wiiu-cheat-codes-here.395443/page-326#post-7191151
