### ISSUE TITLE
BoTW update

### ISSUE THREAD

**Issue by JJmore** [joffnerd/botw-trainer#127]
Looks like the newest update broke the trainer. Upon connecting, the game crashed with a stack error. 

Exception type DSI occured!
![img_0961](https://cloud.githubusercontent.com/assets/28332706/25648054/e50882f2-2f84-11e7-8a45-50296a8a08c3.JPG)

**Comment by wazzusig** [comment]
I haven't updated the game, but I have come across this in the past when I "connect" to the console before launching the game. Have to hard reset every time.

**Comment by JJmore** [comment]
Checked the forum, looks like Mr. Panda will update next week, when he gets home.

**Comment by chariram123** [comment]
I updated to 1.2.0 how to i go back to a update that works? or do i have to wait a week for the update for the trainer?

**Comment by papion23** [comment]
is there any way we can go back to version 1.1.2 i have try lots of thing but cant seen to get download the old update from now on I'm saving all old updates for this game was having lots of fun with this please help. some body that's still have ver 1.1.2

**Comment by JJmore** [comment]
To get old updates you can use the wii u usb helper, it is similar to utikdownloadhelper. It can be found at : https://gbatemp.net/threads/release-wii-u-usb-helper-a-small-eshop-for-windows.446565/ 

Although, when I tried deleting and reinstalling the old update the Wii U kept trying to download the latest update, even while blocking or disconnecting the internet. I think my profile may have stored the latest version number, so reverting may be an issue if you do format your profile.

**Comment by dopeter90** [comment]
How do you format your profile? Do you mean deleting the save file associated with the botw update?

**Comment by JJmore** [comment]
More like, resetting your Wii U to factory. Another way is to edit some files in the nand.

https://gbatemp.net/threads/downgrade-updates-on-wii-u-games.466343/

**Comment by dopeter90** [comment]
Oh, I'd rather not do that after I spent all my time setting up the homebrew on my wii u. Guess I'll just wait until the trainer is updated.

**Comment by piratesephiroth** [comment]
Once you connect to the internet it will retrieve the latest update version for all games and you'll always get the update nag. You can't bypass it.
You should just install the older update and then just ignore the update nag and start the game.

**Comment by JJmore** [comment]
if you use a dns server that blocks the nintendo update sites then it won't check for updates. The issue is if you have upgraded already there is a file on your Wii U that keeps the version info of the games you are playing. So, if you don't edit that file to reflect your update choice, then the Wii U will try and initiate the update process if you are on a lower update then the one indicated on your version file.

**Comment by papion23** [comment]
thanks guys ill just try playing the (EUR) Ver Until trainer is updated to see if that helps hope it those also hope my save file works on it.
