### ISSUE TITLE
Future of the trainer

### ISSUE THREAD

**Issue by Tarog** [joffnerd/botw-trainer#128]
Hey i just wanted to ask if the trainer still has a team working on it.
The last update was 13 days ago and the new zelda update doesnt work with this version of course.
Is there a new trainer that i havent hears of or something?
Thanks in advance

(My english sucks i am from holland)

**Comment by Tarog** [comment]
I found out that you are on vacation i will close the issue

**Comment by joffnerd** [comment]
No worries, i will fix next week when i get chance
