### ISSUE TITLE
BOTW-Trainer FiX for the ones that updated to Ver.80

### ISSUE THREAD

**Issue by papion23** [joffnerd/botw-trainer#129]
Is there any way we can go back to version 1.1.2 I have try lots of thing but cant seen to get to download the old update from ( uTik Download Helper) or (USB Helper) From now on I'm saving all old updates for this game was having lots of fun with this please help. some body that's still have ver1.1.2 update on there SDCard Please Share it ill do the same if this ever happens again thank you guys and have a great day.

![image](https://cloud.githubusercontent.com/assets/28513500/25784641/c5413848-333e-11e7-9a0a-1add50dd67f3.png)

**Comment by papion23** [comment]
ok guys just find a solution for those of  you that updated to the new ver80
https://www.dropbox.com/s/03wxc8fnncmucx7/The%20Legend%20of%20Zelda%20Breath%20of%20the%20Wild%20%5B0005000E101C9400%5D%20%28v64%29.rar?dl=0

**Comment by dopeter90** [comment]
Hey papion23, did applying the old update work for you? I've tried it but the wii u keeps trying to update to new version.

**Comment by papion23** [comment]
dopeter90 no I didn't but I got the Eur. ver to work till they update this one

**Comment by GoodP** [comment]
Hey is the file for returning the game to ver. 1.1.2? That will not work. I am keeping all the updates file since the start of botw. I already did, but If you run back to 1.1.2 after playing 1.1.3 you cannot open the game. it'll say that this game need update to work. We just need to wait for the update of the trainer

**Comment by pchard** [comment]
https://gyazo.com/b0c42425c01f6e075fa43707a6f9b125

**Comment by pchard** [comment]
Cannot download it - See here: https://gyazo.com/b0c42425c01f6e075fa43707a6f9b125

**Comment by ZipZash** [comment]
Just be patient guys. Pandaonsmack's said he will be updating the bot to work with v80 this weekend when he gets back from his vacation

**Comment by joffnerd** [comment]
Try latest version
