### ISSUE TITLE
Still issue

### ISSUE THREAD

**Issue by pchard** [joffnerd/botw-trainer#130]
Hello.

I don't know what it is, me doing it wrongly, or this simply not working still, but..

I open up tcpgecko, press A to load it.
Start up my game, load my save game. 
Waits till I can walk around.
Starts BoTW trainer.
Presses Connect.

Comes up with this error:

Error data will appear here
Connection closed.   ved BotwTrainer.TcpConn.Read(Byte[] buffer, UInt32 nobytes, UInt32& bytesRead)
   ved BotwTrainer.Gecko.ReadDataBufferSize()
   ved BotwTrainer.Gecko..ctor(TcpConn tcpConn, MainWindow mainWindow)
   ved BotwTrainer.MainWindow.ConnectClick(Object sender, RoutedEventArgs e)

Here's a small update:

I used Gecko U Updater, got the latest files.

It connects now, however, updating the time crashes the console.

**Comment by YaFreezy** [comment]
I got the same error everytime. u say it connect now, does it work ?

**Comment by GoodP** [comment]
You're wrong!!!

When you start TCPGecko don't press "A", you should press "X" button install with "codehandler" if I'm not mistaken.

**Comment by pchard** [comment]
If you read the instructions, codehandler is now added within TCPGecko.. So, pressing A is correct.
That works for me anyways.

**Comment by YaFreezy** [comment]
Yes after updating TCPgecko with geckoU everything worked. After updating the option press x to install with codehandler wont be there if u use the latest tcpgecko. It has a buildin codehandler
