### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by wazzusig** [joffnerd/botw-trainer#131]
Before updating to 1.2.0 and 4.0.0 of the trainer, what codes aren't currently working?

**Comment by YaFreezy** [comment]
I tried weapons, Bows, Armors, Rupees, moon jump and everything else.. everything worked for me. I got the EU version updated to 1.2.0 with trainer 4.0.0

**Comment by ZipZash** [comment]
I don't think coordinate are working. I tried to track my coords and got the same error you would get if you used the old version of the trainer for v80

**Comment by joffnerd** [comment]
I just updated to fix wolf code and coordinate stuff
