### ISSUE TITLE
Error Log. Connection closed. Game 1.2.0 Trainer 4.0.0

### ISSUE THREAD

**Issue by YaFreezy** [joffnerd/botw-trainer#132]
Everytime i try to connect to my Wiiu i got this error.

Error data will appear here
Connection closed.   bei BotwTrainer.TcpConn.Read(Byte[] buffer, UInt32 nobytes, UInt32& bytesRead)
   bei BotwTrainer.Gecko.ReadDataBufferSize()
   bei BotwTrainer.Gecko..ctor(TcpConn tcpConn, MainWindow mainWindow)
   bei BotwTrainer.MainWindow.ConnectClick(Object sender, RoutedEventArgs e)

TCP Gecko and everything else should be right..

**Comment by YaFreezy** [comment]
UPDATE: After adding some Values (Rupees and other stuff) the trainer crashed. Game Still running.

**Comment by YaFreezy** [comment]
UPDATE 3: If i try to connect without buffer size, im able to see ingame values on trainer but got this error message: 

Connection closed.   bei BotwTrainer.TcpConn.Read(Byte[] buffer, UInt32 nobytes, UInt32& bytesRead)
   bei BotwTrainer.Gecko.GetServerStatus()
   bei BotwTrainer.MainWindow.ConnectClick(Object sender, RoutedEventArgs e)

**Comment by Giftedly** [comment]
If you're having issues with the 4.0.0 update.
Download Gecko U Updater.
There is a new version of TCPGecko where the codehandler is now merged with the TcPGeko thing itself.
Download that and put that into the SD Card then download the new version of the trainer.

Boot up your game before you connect your trainer. Wait till your save is finished the press connect.
It should work then.

**Comment by YaFreezy** [comment]
Okay Thank you. I'll try it now.

**Comment by YaFreezy** [comment]
It worked. Thank you.
