### ISSUE TITLE
[Feature Request] Spawn Enemies

### ISSUE THREAD

**Issue by Saphiresurf** [joffnerd/botw-trainer#134]
It would be really nice to be able to spawn enemies in. Especially since you can double your attack damage and stuff, it'd be a lot of fun to be able to create a horde in game and try to battle through them either with your damage modifier increased or just with new equipment spawned in.

Something that could be an alternative to this or that could really honestly supplement this (you could sort of make your own bosses out of any enemy with this, too, which would be cool) is if you could change the health and/or other stats of mobs that are sort of spawned around you or angry at you. Whether this be existing mobs around you or maybe just being able to spawn in certain mobs with certain stats to supplement the feature request above. This feature's probably a little less plausible, but could be interesting none the less.

Also thank you guys for your work on this so far, it's really a lot of fun to mess around with :3.

**Comment by Tarog** [comment]
Hi,
this actually already is a fueture,
you need to get the ID of the enemy you want and replace the Normall arrows ID in the trainer with the enemy id and if you save you should be able to spawn enemys
Sorry my english is really bad but i hope i helped you

Here is a link to most enemy IDS 👍 

https://gbatemp.net/threads/botw-item-names-for-pandaonsmacks-trainer.463959/

If this helped you please Close the issue have a good one :)

**Comment by skoolzout1** [comment]
hmmm, i have a code that can replace any object/npc/enemy in the game with any other object/enemy/npc in the game. so you could replace certain objects with a type of enemy you want, and depending on how common the thing you replaced appears on the map would determine how many of those enemies spawn for you.

So you could replace like deer or foxes with ie. ThunderBlight Ganon and you'd run into tonnes of them to fight throughout the overworld.

although this would be a decent amount of work for Panda to add most likely. but if he wants, i could work with him to add that.

**Comment by Saphiresurf** [comment]
Oh that's awesome! I'll go mess around with that then thank you! Is there any possibility of being able to spawn enemy's without it having to replace a currently spawned item? This is pretty cool for other reasons though, just curious if the above might be possible, too ^.
