### ISSUE TITLE
WolfLink Disappearing!

### ISSUE THREAD

**Issue by GoodP** [joffnerd/botw-trainer#135]
Hello there! I noticed about the next update, that whenever you load the game, the arrow/ tool you edited to be the summoner of wolflink is gone. Is there anything I can do, so that, I can summon WolfLink or any other enemy whenever I am playing without opening my pc to edit it again? Thanks!

**Comment by joffnerd** [comment]
Hmm, not sure what you mean? The wolf link health code is re-enabled but nothing has been removed?

**Comment by GoodP** [comment]
What I mean is:
I am using an weapon like sword to summon wolflink. after editing it'll be an unknown item of-course. So Just equip it using the key combo on the controller and the wolflink appears. My problem is, when I quit the game then load again, the item I edited is gone. So I need to have another weapon to edit to become the summoner of wolflink. I just want to know if it is possible to not keep on editing an item to become a summoner, just it will be permanent and no need to open a laptop to edit again.?

**Comment by xNeptune** [comment]
No there is no way to do that. After you change the weapon to an invalid ID and save and load it'll delete said item due to it not being a weapon any longer. There is no permanent way to keep an item that allows summoning of certain NPC's.

**Comment by GoodP** [comment]
Oh I see! But last time, before the update 1.2. It's good, it keeps.
