### ISSUE TITLE
I got the trainer to work once now it keeps failing.

### ISSUE THREAD

**Issue by willebug** [joffnerd/botw-trainer#136]
I was able to get version 4.0.0 to work a few days ago with version 1.2.  I have tried using both version 4.0.0 & 4.0.1 now and keep getting the following errors after trying to enable any codes.

Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at BotwTrainer.TcpConn.Write(Byte[] buffer, Int32 nobytes, UInt32& bytesWritten)
   at BotwTrainer.Gecko.SendCommand(Command command)
   at BotwTrainer.Gecko.WritePartitionedBytes(UInt32 address, IEnumerable`1 byteChunks)

I also get the following error when trying to load the item list.

The calling thread cannot access this object because a different thread owns it.   at System.Windows.Threading.Dispatcher.VerifyAccess()
   at System.Windows.Threading.Dispatcher.DisableProcessing()
   at System.Windows.Documents.TextContainer.BeginChange(Boolean undo)
   at System.Windows.Documents.TextElementCollection`1.Add(TextElementType item)
   at BotwTrainer.MainWindow.LogError(Exception ex, String more)
   at BotwTrainer.Gecko.ReadBytes(UInt32 address, UInt32 length)
   at BotwTrainer.Gecko.GetInt(UInt32 address)
   at BotwTrainer.MainWindow.LoadItemData()

I'm using the newest version of TCP gecko downloaded as you suggested with the updater program.  I have the latest version of the .net framework.  My WiiU and computer are on the same network with my anti-virus and firewall disabled.  I'm not sure what has happened to create this issue.  Any ideas?

**Comment by caljos13** [comment]
I have the same problem

**Comment by o0DeathCon0o** [comment]
So annoying! I have the same problem. I have redownloaded everything multiple times and nothing. Does anyone know of an alternate way to do this? I can't get Breath.exe to work. It always gives me the error that it is corrupted. Any help is appreciated.

**Comment by Tarog** [comment]
Hi 
You are using the wrong tcpgecko
Download the one from Bully
and if that didnt work download mocha CWF that helped me

**Comment by willebug** [comment]
I'm using version 2.2 of tcpgecko and I used bully's tool to download it. I mentioned that it worked once for me and then didn't. I didn't change my version of gecko between. I'm not sure that's the problem.

**Comment by caljos13** [comment]
Are you sure thats correct Tarog, The guide says to uses the updater of bully tcp gecko,  I have the latest version, by using the updater tool and moving the files to the sd card.

**Comment by xNeptune** [comment]
From the sounds of things you aren't running the homebrew correctly. 
Try to use a different homebrew launcher such as loadiine.ovh (not 100% sure this is the address)
and make sure you use the correct launcher corresponding to your firmware. 
From the error you are receiving you can see that you are being denied access to the wiiu.

**Comment by willebug** [comment]
Nothing changed between it working and it not working on my console or my computer. I don't see how your suggestion will help me here. It worked and the next day it didn't. I didn't do anything differently between attempts.

**Comment by caljos13** [comment]
I used Loadiine.ovh on 1.3 and 1.4 homebrew launcher, same thing with w4ml.  Same thing.

**Comment by willebug** [comment]
Ok I got the trainer working again on my system.  I had to run haxchi then mocha then gecko then the game.  It would connect and I could manipulate it as I saw fit.  The mocha part was the part that was eluding me.  Not sure if this will help anyone else having this problem.  This problem for me is closed.  Hopefully everyone else having it can use the above and achieve similar results as me.
