### ISSUE TITLE
The Master Sword issue

### ISSUE THREAD

**Issue by Ilonley** [joffnerd/botw-trainer#137]
Hi, first of all sorry for my bad english. 
Ok, I really hope you can help me... So, when I was In some point of the game, I search the Master Sword... I found it, but I did not have the 12 hearts needed to take it off. So I use the trainer infinite hearts code and it work. So, when I have the sword with me, I teleport out of the forest... When I was outside, the game crash... But before crashing, it saved.
When I came back, I realize that the sword was gone and when I go to the forest I did not find it... It just disappear... Is there anything I can do to get it back? I already try with an old save but, every time I teleport somewhere else the sword disappear. I hope you can understand my bad English. And if you need more information, please tell me!
The Legend Of Zelda - Breath of the Wild (USA)

**Comment by GoodP** [comment]
Pretty easy men! Just go get a weapon, edit it to become the master sword. Then you had it again. The master sword. What happened to you maybe just some kind of error. And this is the easiest way to get the master sword again. Making another one. hahah hope it helps.

**Comment by xNeptune** [comment]
Load up the trainer while in-game. Connect everything and load your items. 
Then go to the weapons tab in the trainer and look through to find a weapon you no longer need.
If you see one you no longer need or want then change what's inside the weapon ID box to "Weapon_Sword_070"
Save and load and you should have a fully functional master sword that won't disappear on you.

**Comment by Ilonley** [comment]
It Work! Thank You!
Jeje, sorry for my ignorance.
