### ISSUE TITLE
tuto ?

### ISSUE THREAD

**Issue by grego31430** [joffnerd/botw-trainer#138]
Can you explain what code do ?

**Comment by skoolzout1** [comment]
which codes? All of the codes do exactly what they say they do, some of them arent very descriptive i guess. but they all work the same. just click the check box beside the codes you want and click save to apply them

**Comment by joffnerd** [comment]
Best place  to find out more is GBA Temp

https://gbatemp.net/forums/wii-u-hacking-backup-loaders.248/
