### ISSUE TITLE
Speed and Moonjump codes

### ISSUE THREAD

**Issue by slmenz90** [joffnerd/botw-trainer#139]
Hello, 

I can't seem to get the speed or moon jump codes working, there are no errors displayed and don't crash the trainer or the game - they just don't seem to activate. 

Is this due to the recent game update? I had never tried to use them before so I'm not sure.

Any help appreciated. 

Thanks

**Comment by Ilonley** [comment]
I have the same issue...

**Comment by Nickd91** [comment]
Is your TCPgecko updated to the latest update? If not try using the updater tool linked in the readme.

**Comment by slmenz90** [comment]
Yeah first thing I checked and have since tried it with a new SD card etc and still no joy

**Comment by Nickd91** [comment]
The controller option setting is correct?

**Comment by slmenz90** [comment]
Yep set correctly

**Comment by Nickd91** [comment]
Your original comment made it sound like you hadn't updated the trainer in a while, you have updated correct? It should prompt you on trainer start up if it is outdated.

**Comment by slmenz90** [comment]
Yeah got the most up to date one - what I meant in the original comment was around wondering if this had been a code that hasn't been moved across because of the recent game update but clearly there's just something wrong at my end cause it's working for others

**Comment by Nickd91** [comment]
I am out of ideas, sorry I was unable to help. Aside from reformatting the SD card and reinstalling the TCPGecko. Do any of the other codes work for you, or is it limited to those two?

**Comment by slmenz90** [comment]
Don't worry about it - will try swapping with my friends SD card, there's seems to work fine 

As far as I know it's just those two, haven't tried the horse code yet but will see - very weird glitch
