### ISSUE TITLE
Freezes

### ISSUE THREAD

**Issue by Nickd91** [joffnerd/botw-trainer#140]
I have been having random freezes using this trainer, requiring a hard reset. The codes work perfectly otherwise. Is there anyway I can get more information from the WiiU so as to diagnose the problem? I am not sure which cheat may be the culprit. The first freeze happened at Eventide Island, I guessed it was a local occurrence and ignored it. The freezes have also been more common since the 4.0.3 update. Is there any further information I can give to help resolve this bug?

**Comment by skoolzout1** [comment]
Hi, most of the codes are mine, and ive heard others have issues with crashing. I believe one of the codes MIGHT be using an unreliable pointer. Im not 100% certain but i have a hunch its the infinite health code. try avoiding that code and using the Mipha's Grace Instant Reset Code instead, and see if the crashing goes away.

unfortunately there's no real way to troubleshoot other than turning off a few codes and seeing if the crashes stop.

**Comment by Nickd91** [comment]
I don't use the health or stamina codes so another code must have been the issue. I was only using durability codes, immunity code, stealth code, moon jump, and the powers timer codes. Unfortunately I can't narrow it down further. I thought it might be the durability codes as when you reach Eventide the game probably moves the inventory pointer, creating a new second inventory causing the illusion that all of your stuff is gone.

Other random freezes I had were mostly me speeding around at 4x speed with the paraglider, not the loading stutters, but ones requiring hard reset. I really don't know why they happened.

Honestly, those aren't enough for me to care all that much because the game autosaves after you do practically anything.
