### ISSUE TITLE
Adding botw-trainer Cafe Codes to JGecko U

### ISSUE THREAD

**Issue by Megabyte918** [joffnerd/botw-trainer#144]
First off I just want to thank @joffnerd for continuing to work on this project, it's been really great to play around with this trainer in BotW and I've been having so much fun with it :)

I just have one question regarding the Cafe codes the trainer sends to the Wii U.

I've recently stumbled upon [this](https://www.youtube.com/watch?v=phRtaSpdY2M) code that lets you spawn anything you want, it's been really fun to use along with the trainer. The only problem I have is, since JGecko U and this Trainer both need to connect to the same port from the Wii U, I can't use the Accio code and the Trainer at the same time. It's either one or the other, or I keep having to disconnect one or the other to play around with both codes. 

So since I can't add the Accio code to the trainer, I thought I'd add the codes from here to JGecko U so I could enable the cheats from here, along with the Accio code(s) and play around with both rather than only one at a time. 

The problem is, I do not know how to add the codes from here to JGecko U. I've taken some looks at the [Codes.cs](https://github.com/joffnerd/botw-trainer/blob/master/Codes.cs) file to try to add them but it just doesn't add up for me. 

```js
`Take the "stamina" code for example:`

// Max 453B8000
var value = uint.Parse(mainWindow.CurrentStamina.Text, NumberStyles.HexNumber);

codes.Add(0x00020000);
codes.Add(0x424527A4);
codes.Add(value);
codes.Add(0x00000000);

codes.Add(0x00020000);
codes.Add(0x424527A8);
codes.Add(value);
codes.Add(0x00000000);

`The format for adding a Cafe code into JGecko U is as follows:`

XXXXXXXX XXXXXXXX
YYYYYYYY YYYYYYYY
ZZZZZZZZ ZZZZZZZZ
etc

`So If I wanted to add this stamina code into JGecko U as a Cafe code, would I format it like this?`

00020000 424527A4
 VALUE   00000000
00020000 424527A8
 VALUE   00000000

`Or maybe like this?`

00020000 00020000
424527A4 424527A8
 VALUE    VALUE   
00000000 00000000

`And what would be the value of the "value" variable? Where can I find it?`
```
I have so many questions >.< I figured I'd ask you since you have much more experience than I do with this sort of stuff. Thanks for taking the time to read :)

**Comment by skoolzout1** [comment]
About 90% of the codes were made by me, you can find the list of them all in the jgecko format on my pastebin here:
https://pastebin.com/GhVJX4ZY

Go to your version of the game and copy and paste the codes as plain text into jgecko. 

If the code you're taking from the trainer isn't one of mine, then you put them together 8digits at a time, 16 digits per row with a space between each 8.

In other words, your second example you used was the correct way.

For more information on the cafe code type format, see the creators documentation: http://cosmocortney.ddns.net/enzy/cafe_code_types_en.php#not


The values to replace in the codes vary between codes, most often they are just float values. You can go to jgecko, click the conversions tab, click the Floating point -> Hexidecimal button, then type the value you want and copy the hexidecimal version that it spits out and put it into the code.

For the stamina code you copied, you'd put a value of 3000 converted into a floating point (453B8000) for max stamina

**Comment by Megabyte918** [comment]
@skoolzout1 Thank you so much! I was actually experimenting with this about an hour ago and managed to successfully format about half the codes on my own because of what I saw in [this commit](https://github.com/joffnerd/botw-trainer/commit/a1adf62d6a5f1d53100da1556735a34b72949bea#diff-12168c3bfbc1fcbb2dca9e211c90d17c) (yay im learning!)

But with your pastebin it will be much quicker to input the codes! Along with some new ones I haven't seen before >;D

Also thanks for explaining how the hex and unknown hex values work, maybe I can make my own cheats someday :)

**Comment by CCF100** [comment]
@skoolzout1 How would I change the 1.3.0 code "B to run fast" to work with the pro controller?

**Comment by skoolzout1** [comment]
If you're using this code as a reference,

30000000 3F93B768
417A9202 45876E2D
31000000 000000CC
00120000 3F800000
09010000 102F48AA
00004000 00000000
00120000 40C00000
D0000000 DEADCAFE


Then you change the following.

30000000 3F93B768
417A9202 45876E2D
31000000 000000CC
00120000 3F800000
09010000 ADDRESSS
BUTTON 00000000
00120000 40C00000
D0000000 DEADCAFE

So you'd replace the Address Line with whatever the pro controller address is. I don't know it. And you replace the button portion with the button you want to use to activate 


A =00000010
Y =00000020
X = 00000008
B = 00000040
- = 00001000
+ = 00000400
R = 00000200
ZR = 00000004
L = 00002000
ZL = 00000080

Hopefully that helps. Sorry that I don't know the Pro controller address

**Comment by skoolzout1** [comment]
I replied on my phone and it messed up the formatting but the first Bullet Is the minus button and the second bullet is the plus button if you wanted those for some reason

**Comment by CCF100** [comment]
Odd. May just be a coincidence, but the code below causes my Wii U to lock up...
30000000 3F93B768
417A9202 45876E2D
31000000 000000CC
00120000 3F800000
09010000 112B4FA2
00004000 00000000
00120000 40C00000
D0000000 DEADCAFE

**Comment by skoolzout1** [comment]
Alright. Send me a dump of your game from 10000000 to 4C8A0000.

Just a bad pointer I guess. I'm guessing you're using a PAL version of the game?

**Comment by skoolzout1** [comment]
It'll probably take about 20-30 minutes for you to dump the game. Then you can just zip it or compress it into a Rar file and upload it to some file sharing site and post the link. 

Also how many times did you test it? Would you say that it's probably pretty close to a 100% chance that it'll crash upon using that code?

**Comment by CCF100** [comment]
Actually, it's an NTSC version. Dumping it now...
