### ISSUE TITLE
Will you update the trainer for the DLC?

### ISSUE THREAD

**Issue by Tarog** [joffnerd/botw-trainer#146]
In about 2 days from now the new DLC wil hit the eshop and i was wondering if you would update the trainer if you aren't going to do that i need to duplicate everything right now :)

**Comment by skoolzout1** [comment]
We're working on it.. give us some time.

**Comment by chariram123** [comment]
I keep hearing everywhere thst they stop working on the botw trainer or gave up

**Comment by joffnerd** [comment]
I updated it today thanks to skoolzout1's codes
