### ISSUE TITLE
DLC update please

### ISSUE THREAD

**Issue by snow78000** [joffnerd/botw-trainer#149]
Hello !
It's been 4 days since the DLC came out :p
It's amazing, but do you think you can update the Trainer ? Because it doesn't work anymore and it was awesome :/
Thanks by advance :)

**Comment by skoolzout1** [comment]
Yupp. It takes time and me and Joffnerd both have lives lol.

**Comment by snow78000** [comment]
Hi ! :p
Thank you !
You guys are awesome !!! :D
Yeah, don't forget to live xD
Tell me when you'll release a new version please ;p

**Comment by skoolzout1** [comment]
If you click "Watch" on the thread you can receive notifications of when updates occur

**Comment by snow78000** [comment]
Okay ! Thanks ! :p

**Comment by windygeko** [comment]
Hey everyone, hate to be impatient but I was curious, is there a planned inbound fix for the DLC updates or whatever cuz y'kno nintendo ruins all our fun breaking they're games :c either way keep up the good work you guys provided an awesome tool for an epic game

**Comment by Bleak-Expert** [comment]
Yeah thanks for giving us something really fun to do in botw!

**Comment by AP-Crazy13** [comment]
So now we can use the trainer with the old dlc?

**Comment by joffnerd** [comment]
Trainer updated for 1.3
