### ISSUE TITLE
Cannot get more hearts or rupees

### ISSUE THREAD

**Issue by mazenashi** [joffnerd/botw-trainer#150]
I am able to edit all weapons, food shields and materials, however in the code tab no mater what I try to change the changes don't take effect. can you help please?

**Comment by skoolzout1** [comment]
Which version of the game are you on?

**Comment by mazenashi** [comment]
v 1.3.0

**Comment by Scottwaine** [comment]
trainer only works on V1.2.0

**Comment by mazenashi** [comment]
anything for 1.3?

**Comment by joffnerd** [comment]
Trainer updated for 1.3
