### ISSUE TITLE
Crash on connecting

### ISSUE THREAD

**Issue by GoldenDustFox** [joffnerd/botw-trainer#151]
I tried connecting my Wii U to the trainer using the latest version, and got a crash as a result. I have the log copied from the trainer's Error Log.

I'm using the latest version of BoTW (Ver.1.3.0) and have the latest DLC pack installed (DLC Ver.2.0)

[Error Log.txt](https://github.com/joffnerd/botw-trainer/files/1124016/Error.Log.txt)

**Comment by Scottwaine** [comment]
The trainer will only connect to V1.2.0 (v80) not 1.3.0(v97).

**Comment by joffnerd** [comment]
Trainer updated for 1.3
