### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ezequielprezz** [joffnerd/botw-trainer#152]
It Keeps on giving me an error since i Updated the game. Are you guys going to update the trainer?

**Comment by snow78000** [comment]
Look at the other issues ;)
They will, but it's a hard work :p

**Comment by chariram123** [comment]
I hear they stopped working on the trainer. So no more botw trainer.. I am sad. It's was the only thing that I use anymore.

**Comment by xNeptune** [comment]
Not sure where you "heard" that but it's not true. It's being worked on

**Comment by chariram123** [comment]
I hear it all over facebook, discord and other websites all about botw trainer.

**Comment by skoolzout1** [comment]
There's a BoTW trainer discord?

Also not to sound cocky, but unless you hear me or joffnerd specifically say we aren't updating it, then nobody else would be able to say with certainty that it's not going to be updated, lol.

**Comment by windygeko** [comment]
So...your confirming update then for all of us lowly scrubs who worship
your work?

**Comment by skoolzout1** [comment]
Well shucks, when you put it that way, how could I resist? Lol.

Lots of people must be having trouble with the trials I'm guessing which is why everyone is losing their minds to have it updated.

**Comment by windygeko** [comment]
Less trouble with the trials more I miss setting x32 speed and breaking
links model in hilarious ways lol I mean either way your coding is solid
and your trainer was fucking fantastic, I do wish there were an update but
what am I gonna do, bitch? Nah son that ain't getting us anywhere all I can
do is what any of us can, and pray.

**Comment by skoolzout1** [comment]
Hahaha, well to be clear, it's not my trainer, it's joffnerd/PandaOnSmack's trainer. He designed and programmed the trainer. I make/update the codes in the trainer.

**Comment by windygeko** [comment]
Fair enough even so its very nice and well put together while I am looking
forward to an update for the dlc I can still appreciate what we've had

**Comment by chariram123** [comment]
I can't beat the master sword trail. And yes there is I am in it in discord. ( ps. I made it but nobody is in it because they hate hacking botw ) if you want a link to the discord let me know.

**Comment by chariram123** [comment]
Link to the discord. 

https://discord.gg/uzyUf

**Comment by KingxDhruv** [comment]
I would also like a link to the discord please. Thank you 😁👍

**Comment by chariram123** [comment]
I posted it in here.
The people who made the trainer gets set as makers aka yhe campins. 
Others are set as nothing. 
I am set as the hero because I made the discord for botw trainer. Just need everyone that made the trainer to join in if they want so it can be set

**Comment by KingxDhruv** [comment]
Discord says that the link has expired

**Comment by chariram123** [comment]
New Link:
https://discord.gg/6dN5EKy
Set to never Expires

**Comment by chariram123** [comment]
This is turning into a chat so that''s why I made a discord for it

**Comment by KingxDhruv** [comment]
Thankyou

**Comment by joffnerd** [comment]
Trainer updated for 1.3
