### ISSUE TITLE
Future updates

### ISSUE THREAD

**Issue by Tarog** [joffnerd/botw-trainer#153]
Hey 
I know skoolzout and joffnerd are working on the new update DLC PACK 1 and i apriciate that

But i was wondering if you would do the same for DLC 2 i know thats months away but i would like to know :) 

Thx for the conetant updates on the trainer

**Comment by iTzKishouArima** [comment]
Idk i think yes so, we shall wish that

**Comment by joffnerd** [comment]
If it isn't a lot of work, yes. Hopefully they wont change too much again
