### ISSUE TITLE
References for item values

### ISSUE THREAD

**Issue by scj643** [joffnerd/botw-trainer#155]
The web save editor has a table of all the hex values for things like items. https://github.com/marcrobledo/savegame-editors/blob/master/zelda-botw/zelda-botw.data.js is where that can be found.

**Comment by joffnerd** [comment]
OK, what are you suggesting?

**Comment by scj643** [comment]
If a value matches in the category show it

**Comment by joffnerd** [comment]
That file works off the save data which is stored in a different way / order. What do you want from it?

**Comment by scj643** [comment]
What I want for it is say the modifiers for weapons some sort of indicator of what that modifier is would be nice.
