### ISSUE TITLE
Moonjump not works

### ISSUE THREAD

**Issue by AP-Crazy13** [joffnerd/botw-trainer#156]
I try to activate it but it doessn't work... btw good job really!!

**Comment by iTzKishouArima** [comment]
You hace activated PRO CONTROLLER Mode on trainer?

**Comment by AP-Crazy13** [comment]
nope...

**Comment by AP-Crazy13** [comment]
Now it's works thanks

**Comment by iTzKishouArima** [comment]
Its nothing
