### ISSUE TITLE
application crashes

### ISSUE THREAD

**Issue by ezequielprezz** [joffnerd/botw-trainer#157]
whenever I start it, it automatically crashes
![image](https://user-images.githubusercontent.com/29646907/28047603-145d3d80-65a0-11e7-9376-9ed07b58328d.png)

**Comment by iTzKishouArima** [comment]
Well, I think you need to run the trainer on the file.

**Comment by joffnerd** [comment]
What .net version do you have? What does  it say in the View Details bit?

**Comment by alfredogomez35** [comment]
Try renaming the app.release folder to something else. The same thing used to happen to me but renaming the folder fixed everything.
