### ISSUE TITLE
Codes tab (or just currency) bug?

### ISSUE THREAD

**Issue by systemeth** [joffnerd/botw-trainer#158]
Changing my rupee or mon amount doesn't work anymore for some reason.
The program doesn't error or anything, just nothing happens.
I'm using the latest version, and it works for other stuff (I gave myself some amiibo stuff for example) just fine.
Just not what I tried in the Codes tab, being the currency amounts.

**Comment by skoolzout1** [comment]
Did it work before? How often does it stop working?

**Comment by systemeth** [comment]
It used to work with the older version, as in before it was updated for the latest game update.
I'm trying this with my Master Mode save file, but I can't see how that would change anything if I was able to give myself some amiibo items just fine.

**Comment by skoolzout1** [comment]
Hmmmm well. It wouldn't hurt to try your regular profile to see if the rupees works. If it does then maybe it's just an issue with master mode and I'll have to maybe look into it. Are you PAL or NTSC? In other words, basically are you European or Canadian/American?

**Comment by systemeth** [comment]
Okay, I tried my regular profile. It's not doing it there either. I'm NTSC.

**Comment by skoolzout1** [comment]
Alright, do you have Jgecko U?

**Comment by systemeth** [comment]
Yes

**Comment by skoolzout1** [comment]
Would you be able to dump your game from 3F000000 to 49000000 and send it to me then?

**Comment by skoolzout1** [comment]
Or if you want you could do a full dump from 10000000 to 4C8A0000 but it doesn't matter

**Comment by systemeth** [comment]
I already started the first dump.

**Comment by systemeth** [comment]
Also I had just left the memory range at custom (what it was on by default for me) instead of code or data. That won't mess with anything will it?

**Comment by systemeth** [comment]
Well the dump is finished.
http://puu.sh/wGLyp/a755824ec1.rar

**Comment by skoolzout1** [comment]
That's fine. I'll take a look at it tomorrow. While you took the dump were you currently trying to use the rupees code?

**Comment by skoolzout1** [comment]
Also how many rupees did you have when you took the game dump?

**Comment by systemeth** [comment]
I was not trying to use the code, but I was using the same file I had attempted to use the code on (without restarting or anything).
I had 23625 at the time of the dump.

**Comment by skoolzout1** [comment]
alright, well i found the time to take a look right now and i was able to see your rupees at 23625, as well as your mon being at 788. And they were both in the correct places in order to be written to. 

Sooo that could a few things, either it happened to be working correctly at the time that you took the dump, in which case I have no way  of knowing what went wrong before.

Or potentially, Panda made a mistake in the trainer? I assume you haven't tested my code for it in jgecko?

if not its:

Infinite Rupees
00020000 3FF52244
0001869F 00000000

Infinite Mon
00020000 3FF52984
0001869F 00000000

If these do not work for you, go to the addresses listed in the second set of digits (so 3FF52244 for rupees) via the Memory Viewer tab in jgecko and switch the View Mode  to decimal, and you should see your rupee count at that particular address. If it IS present at that address but the code doesn't appear to be working.... Then I feel like maybe you're confused lol (no offense).

If my codes do work for you using Jgecko, and it doesnt work in Panda's trainer then it must be something in the trainer.

**Comment by skoolzout1** [comment]
If my codes do NOT work for you, and you go to the addresses and do NOT see the correct rupee count in those addresses. Then send me a dump of your game in that moment again from 3F000000 - 49000000

That way we can capture it acting strangely and correct it.

**Comment by systemeth** [comment]
I'm in Trial of the Sword right now (as after I gave up I simply started playing) so I'll have to test it out a bit later, but I'll give it a try.

**Comment by systemeth** [comment]
Okay I've activated the codes, went and bought some stuff, and my rupee count went down like normal. So I don't think the code worked. In the memory viewer my rupee count is indeed where it's supposed to be.

**Comment by systemeth** [comment]
Fffffuck. It was user error on my part. I forgot that TCPGecko needed to install with Cosmo Courtney's code handler. Sorry for wasting your time.

**Comment by EpicLPer** [comment]
Actually, this shouldn't be closed and mentioned in the Readme on the project page so others won't get confused either. With a link for the download too.

**Comment by systemeth** [comment]
Okay I've reopened it. I've also noticed that the currency change doesn't stick after reloading. Like, while the current file has been affected by the trainer, it will hold your rupee count at whatever you changed it to just fine. But upon reloading it will be back to whatever it was originally. It used to be that your rupee count would stay changed upon reload, but not anymore it seems.

Perhaps there's a second value somewhere?

**Comment by 0100100001001001** [comment]
@ systemeth

The most current version of TCPGecko automatically activates the codehandler, so if you are still having an option not to activate the codehandler you need to update TCPGecko.

**Comment by Bleak-Expert** [comment]
For me when I activate the master sword glow my game crashes

**Comment by skoolzout1** [comment]
People have said there are issues with that code that come from beating the trials already. Not much I can do about it. And I haven't beat the trials yet so I haven't been able to see if I can fix it. (I'm trying to do the trials legit and it's hard lol. I'm stuck on the final trial)

**Comment by Bleak-Expert** [comment]
I wish I could do trial of the sword in looks so fun
