### ISSUE TITLE
Removed all my key items

### ISSUE THREAD

**Issue by trdpatrick** [joffnerd/botw-trainer#16]
I was using 2.0 to modify weapon durabilities and didnt notice that it cleared out all my key items.  Is there a way to edit it back into my save?

**Comment by Gadorach** [comment]
Just thinking here, but you could go get an orb from a shrine, edit it to be the needed key item, then go get another, etc, until you have them all back.

**Comment by joffnerd** [comment]
See GBA Temp for how someone else fixed this.
