### ISSUE TITLE
Python API

### ISSUE THREAD

**Issue by scj643** [joffnerd/botw-trainer#160]
I was thinking about making a python version of the trainer that can be used to programmatically edit stuff. Where should I look at to get started?

**Comment by skoolzout1** [comment]
Uhhhh, what about the trainer needs to be edited?

**Comment by scj643** [comment]
Nothing this would be a separate thing.

**Comment by joffnerd** [comment]
I am new to this myself really. I took a lot from  Bully's jGecko. Also having code from tcp gecko.net helped.

You would need to start with tcp connection code to your wii then you can start to talk to the server bully made that's part of the codehandler

The server responds to lots of commands you send it, bully would have to tell you more

Server commands
https://github.com/BullyWiiPlaza/tcpgecko/blob/master/src/tcp_gecko.cpp#L34
