### ISSUE TITLE
Codes and error

### ISSUE THREAD

**Issue by GamingStormNL** [joffnerd/botw-trainer#162]
When Im using an code nothing happens I tried other versions where it still worked but if I use them then the wii u will crash with Exception something like that

**Comment by EpicLPer** [comment]
Are you using the latest version of BotW?

**Comment by GamingStormNL** [comment]
Yes EpicLPer

**Comment by GamingStormNL** [comment]
changing some armor or weapons from old shirt to something else works but codes don't and sometimes it gives error and freezes wii u/crash

**Comment by GamingStormNL** [comment]
@EpicLPer

**Comment by skoolzout1** [comment]
Ya gotta update TCPgecko. If the Wii ever crashes and displays a message then it very very likely means TCPgecko needs an update. Download the TCPgecko-master folder and place it in wiiu/apps on your sd card from here https://github.com/BullyWiiPlaza/tcpgecko

**Comment by GamingStormNL** [comment]
@skoolzout1 got it but why does the codes not works??
 And Im going to test it now

**Comment by GamingStormNL** [comment]
@skoolzout1 Thanks it worked and the codes works now to!
