### ISSUE TITLE
Can't open the application, instant crash when opened.

### ISSUE THREAD

**Issue by Cosmospeed** [joffnerd/botw-trainer#163]
Hi, I think this issue maybe a useless one but I've spent way too much time searching this error with no results.

So my problem is : I downloaded the latest version of Botw trainer and when I open it it leaves me an error which says : 
`  Problem signature: `
`  Problem Event Name:	CLR20r3 `
`  Problem Signature 01:	BotwTrainer.exe ` 
`  Problem Signature 02:	1.0.0.0 ` 
`  Problem Signature 03:	5968ad37 ` 
`  Problem Signature 04:	PresentationCore ` 
`  Problem Signature 05:	4.7.2053.0 ` 
`  Problem Signature 06:	58fa7581 ` 
`  Problem Signature 07:	149e ` 
`  Problem Signature 08:	40 ` 
`  Problem Signature 09:	System.DllNotFoundException ` 
`  OS Version:	6.3.9600.2.0.0.256.48 ` 
`  Locale ID:	1036 ` 
`  Additional Information 1:	6dd2 ` 
`  Additional Information 2:	6dd2ae3fa855e405b3b89c71cf6d53c5 ` 
`  Additional Information 3:	1716 ` 
`  Additional Information 4:	1716448cad28d0aa17ace73c42449e71 ` 

Any help would be gladly appreciated. 

Have a nice day !

**Comment by joffnerd** [comment]
What OS  is it? What .net version do you have?

**Comment by Cosmospeed** [comment]
OS is Windows 8.1 and I have .net 4.7. It's supposed to be working but I don't get what's missing and why does it crash

**Comment by Cosmospeed** [comment]
Nevermind, the issue is fixed as of now. A windows update package containing the .NET Framework 4.7 fucked everything up so all I had to do was to delete that update and get the .NET Framework 4.7 setup from Microsoft's site. I don't remember the exact windows update package that was missing everything up though.
