### ISSUE TITLE
"Wrong IP"

### ISSUE THREAD

**Issue by mariochristo03** [joffnerd/botw-trainer#166]
I have all the files I need, all the latest  version, have breath of the wild 1.3, have 5.5.1 system version. But whenever I load botw trainer it keeps saying "Wrong IP" and I am 100% sure it is the IP that I got from tcpgecko

**Comment by skoolzout1** [comment]
Well if you're absolutely sure you have the right IP then really the only other thing it could be is like your antivirus blocking the connection. Or maybe TCPgecko needs to be updated. 

The program works fine. So it's just something you're missing

**Comment by mariochristo03** [comment]
This is probably a dumb question, but where do I get the latest version of TCPGecko? Because when I try to search for it, it says the latest release was almost a year ago.

**Comment by xNeptune** [comment]
https://github.com/BullyWiiPlaza/Gecko-U-Updater           
https://github.com/BullyWiiPlaza/Gecko-U-Updater/blob/master/Gecko%20U%20Updater.jar?raw=true

First link brings you to the gecko updater to explain how to use it and the second is a download link for the gecko updater itself. If you need any more explanation feel free to comment again but I think you'll be able to figure out how to use this.
