### ISSUE TITLE
Changing values on Materials/Codes always crashes game.

### ISSUE THREAD

**Issue by rEd2k** [joffnerd/botw-trainer#17]
Hello, I used this excellent trainer for a little while and everything worked fine. After playing the game for some time and progressing forward, the trainer and the game/wii u both have started to crash every single time I try to edit any Material amounts and now any Codes as well. Everything else seems to work fine after an edit and the game wont crash.

Any ideas? I am using your very latest version 2.3.1 and have played with previous versions (which all crash as well now). I am playing the US version and it's installed via the Wii U Nand and I don't have a physical disc copy. 

Thank you for your hard work and time and attention ;)

**Comment by Boldboro** [comment]
Both my game and the program crashes whenever I try to edit anything now:
http://oi65.tinypic.com/zur3i1.jpg

**Comment by joffnerd** [comment]
Ive added some error catching to log whats happening

**Comment by Boldboro** [comment]
Where can I see the log to post it?

**Comment by joffnerd** [comment]
Error tab

**Comment by Boldboro** [comment]
Exception of type 'BotwTrainer.ETCPGeckoException' was thrown.

And before you ask, no... it didn't disconnect.
No I didn't open any other trainers or gecko or anything before or after this.

**Comment by Boldboro** [comment]
Exception of type 'BotwTrainer.ETCPGeckoException' was thrown. once again trying to modify armor to something else.
It's changing the durability of my weapons, but it's not changing them to the item I tell it to change to.

**Comment by rEd2k** [comment]
I also get the "Exception of type 'BotwTrainer.ETCPGeckoException' was thrown." message, though I don't seem to have as many problems as Boldboro does. I only have issues when I edit the Materials and the Codes, everything else works without crashing. In fact All I have to do is just click on either the materials or codes tabs and not even change anything and just click the save button and pow! Crash!

In case this helps, I used to be able to use the Shinzuya/GamePil trainer perfectly here: https://gbatemp.net/threads/the-legend-of-zelda-breath-of-the-wild-trainer-eshop-eu-beta.463066/ and for reasons that are unknown it also crashes the game now as well and can no longer load items in the list (but the other cheats like freezing health and stamina still work and always have).

It's strange but both trainers have starting giving me issues around the same time all of the sudden both wouldn't edit and both would crash, I'm wondering now if it is "linked" (sorry for the pun) to a point in the game where something had changed along the way. Maybe using either trainer to edit things can mess up the state of which the saved game is affected and can cause a cascade on future saves and trainer edits that are expected to work... Just a guess though.

The other error I can report is what shows up on the screen once a crash has happened it says: 

Illegal command byte received: 0x7b
Server Version: 02/25/2017

Hope that helps, I will update if I find a different error from the trainer or output from the Wii U error screen.

**Comment by joffnerd** [comment]
Thanks this is very helpful. I also think this is the issue in some way. I am early in the game so perhaps when I get to the same point as you I will face the issue. Also the gecko code is not mine, it's from the ported tcpgecko so perhaps it has bugs. Over the next week I'm  going to try to add as much detail to error log as possible to see what it is.

**Comment by rEd2k** [comment]
I am glad to be of service good sir ;) I edited my previous post and added some more info if you haven't read it yet -thank for your hard work!

**Comment by rEd2k** [comment]
Ok so with your new trainer and more error codes available I now get this:

Exception of type 'BotwTrainer.ETCPGeckoException' was thrown.   at BotwTrainer.TCPGecko.Dump(UInt32 startdump, UInt32 enddump, Stream[] saveStream)
   at BotwTrainer.TCPGecko.peek(UInt32 address)
   at BotwTrainer.MainWindow.DebugData()
   at BotwTrainer.MainWindow.SaveClick(Object sender, RoutedEventArgs e)

These are the exact same error codes that the user Sapphireflames has reported (but he did not report if he is using the PAL or US version and if his game is up to date or not). Though as usual, I can still use everything like before except any material changes or code/cheats. those still crash as usual.

There is one difference though, I reported that the items would appear from last to first top to bottom in the trainer after a refresh, but now they appear as first is first and last is last top to bottom in the trainer display :) Now maybe you just a made a cosmetic change but I thought I should tell you ;)

Oh and speaking of cosmetic changes, I forgot to mention that I really like the simple dotted lines around all boxes, it was a nice touch and does a great job of making it easier to see where the line match up, thanks for that simple yet very effective visual enhancement :P 

Oh and in case it has been forgotten, I am using the US version with the latest 1.1 (v33) update of the game and no DLC, and always your latest trainer version (in this case 2.3.3). The error on screen after the usual crash is still the same one I posted about earlier:

Illegal command byte received: 0x7b
Server Version: 02/25/2017

No change there. Will report back if I find anything else, keep up the good work ;)

**Comment by joffnerd** [comment]
New version which should help identify where exactly this happens

**Comment by rEd2k** [comment]
I was able to edit my apples to x10 and it stuck and I was getting very excited!
But alas, it seems to be random if the game will crash. This is funny part, the new trainer (2.3.4) NEVER crashed through all my testing. I never got one error code to report from the trainer itself, instead the game always crashed and I do have a few different codes displaying now here they are:

Illegal command byte received: **0xXX** <---This would change to these values below:
Server Version: 02/25/2017

0x7d Just the apple edit ok with x10 then tried to edit a second material to x10 then crash :(
0x2a All materials edited at one time to x990 each, crash
0x2a Just the apple edited to x99 apples, crash
0x7b Just the apple edited to x10 apples, crash
0x12 Edited Fairies to just x1 from x897 (Saved that way previously), crash

Sadly this was starting to seeming appear random and hard to track down, I was really hoping to get something back from the trainer itself but not one time did it report anything in the error tab. Also, all other items are still able to be edited in other tabs, again it's just the Materials and the Codes that are still affected for me.

We are getting closer now, I can feel it, since the apple edit worked more than a few times already, but for the most part always crashed anyways. I did try to refresh the data after every edit to be sure, and I also tried without refreshing just to see if anything would show a better result. In all cases mostly a crash and very few stable edits that stuck.

I'm going to see if I can get an edit to stick and quickly save and then try to edit again from that save, it's hard getting one to stick, but if it does I'm hoping maybe after loading a successful edit from previously maybe I can get it to work properly. Just a wish and a dream but worth a shot right now.

**Comment by rEd2k** [comment]
Lol just saw your 2.3.5 version posted right after I made my last post, I will try it right now! :)

**Comment by rEd2k** [comment]
OK! I got a crash again, but this time I got an error code to give to you from the trainer itself :)

Shield Slot CodeException of type 'BotwTrainer.ETCPGeckoException' was thrown.   at BotwTrainer.TCPGecko.Dump(UInt32 startdump, UInt32 enddump, Stream[] saveStream)
   at BotwTrainer.TCPGecko.peek(UInt32 address)
   at BotwTrainer.MainWindow.DebugData()

The on screen error code is as follows:

Illegal command byte received: 0x7b <-- This seems to be the most common code for some reason
Server Version: 02/25/2017

Will try some more testing now :P

**Comment by joffnerd** [comment]
Nice one, can you screenshot the codes tab for me please? How many shield slots have you got?

**Comment by rEd2k** [comment]
Sorry for the delay, was busy.

I have only 4 shield slots, and here is the requested screen shot for you:

https://1drv.ms/i/s!AtPipJ44eLuQjRAD8YL4HGsm_zKM

I am now testing your latest release (2.5.2) and will report back when I get a chance ;)

**Comment by rEd2k** [comment]
Wow, the materials no longer crash!! GOOD WORK!! ;)

Also, I then did try to change a code in the codes tab, I keep using the rupees as a test only. Unfortunately it did crash :(

Here is the error output from trying to edit rupees to 999,999 and freezing them with the check box:

Stamina Code
Exception of type 'BotwTrainer.ETCPGeckoException' was thrown.   at BotwTrainer.TCPGecko.Dump(UInt32 startdump, UInt32 enddump, Stream[] saveStream)
   at BotwTrainer.TCPGecko.peek(UInt32 address)
   at BotwTrainer.MainWindow.DebugData()

Health Code
Exception of type 'BotwTrainer.ETCPGeckoException' was thrown.   at BotwTrainer.TCPGecko.Dump(UInt32 startdump, UInt32 enddump, Stream[] saveStream)
   at BotwTrainer.TCPGecko.peek(UInt32 address)
   at BotwTrainer.MainWindow.DebugData()

Rupee Code
Exception of type 'BotwTrainer.ETCPGeckoException' was thrown.   at BotwTrainer.TCPGecko.Dump(UInt32 startdump, UInt32 enddump, Stream[] saveStream)
   at BotwTrainer.TCPGecko.peek(UInt32 address)
   at BotwTrainer.MainWindow.DebugData()

Mon Code
Exception of type 'BotwTrainer.ETCPGeckoException' was thrown.   at BotwTrainer.TCPGecko.Dump(UInt32 startdump, UInt32 enddump, Stream[] saveStream)
   at BotwTrainer.TCPGecko.peek(UInt32 address)
   at BotwTrainer.MainWindow.DebugData()

Run Code
Exception of type 'BotwTrainer.ETCPGeckoException' was thrown.   at BotwTrainer.TCPGecko.Dump(UInt32 startdump, UInt32 enddump, Stream[] saveStream)
   at BotwTrainer.TCPGecko.peek(UInt32 address)
   at BotwTrainer.MainWindow.DebugData()

Speed Code
Exception of type 'BotwTrainer.ETCPGeckoException' was thrown.   at BotwTrainer.TCPGecko.Dump(UInt32 startdump, UInt32 enddump, Stream[] saveStream)
   at BotwTrainer.TCPGecko.peek(UInt32 address)
   at BotwTrainer.MainWindow.DebugData()

Weapon Slot Code
Exception of type 'BotwTrainer.ETCPGeckoException' was thrown.   at BotwTrainer.TCPGecko.Dump(UInt32 startdump, UInt32 enddump, Stream[] saveStream)
   at BotwTrainer.TCPGecko.peek(UInt32 address)
   at BotwTrainer.MainWindow.DebugData()

Bow Slot Code
Exception of type 'BotwTrainer.ETCPGeckoException' was thrown.   at BotwTrainer.TCPGecko.Dump(UInt32 startdump, UInt32 enddump, Stream[] saveStream)
   at BotwTrainer.TCPGecko.peek(UInt32 address)
   at BotwTrainer.MainWindow.DebugData()

Shield Slot Code
Exception of type 'BotwTrainer.ETCPGeckoException' was thrown.   at BotwTrainer.TCPGecko.Dump(UInt32 startdump, UInt32 enddump, Stream[] saveStream)
   at BotwTrainer.TCPGecko.peek(UInt32 address)
   at BotwTrainer.MainWindow.DebugData()

**Comment by rEd2k** [comment]
Here is another error output from me simply freezing the hearts with the check box and clicking save:

Stamina Code
Exception of type 'BotwTrainer.ETCPGeckoException' was thrown.   at BotwTrainer.TCPGecko.Dump(UInt32 startdump, UInt32 enddump, Stream[] saveStream)
   at BotwTrainer.TCPGecko.peek(UInt32 address)
   at BotwTrainer.MainWindow.DebugData()

Health Code
Exception of type 'BotwTrainer.ETCPGeckoException' was thrown.   at BotwTrainer.TCPGecko.Dump(UInt32 startdump, UInt32 enddump, Stream[] saveStream)
   at BotwTrainer.TCPGecko.peek(UInt32 address)
   at BotwTrainer.MainWindow.DebugData()

Rupee Code
Exception of type 'BotwTrainer.ETCPGeckoException' was thrown.   at BotwTrainer.TCPGecko.Dump(UInt32 startdump, UInt32 enddump, Stream[] saveStream)
   at BotwTrainer.TCPGecko.peek(UInt32 address)
   at BotwTrainer.MainWindow.DebugData()

Mon Code
Exception of type 'BotwTrainer.ETCPGeckoException' was thrown.   at BotwTrainer.TCPGecko.Dump(UInt32 startdump, UInt32 enddump, Stream[] saveStream)
   at BotwTrainer.TCPGecko.peek(UInt32 address)
   at BotwTrainer.MainWindow.DebugData()

Run Code
Exception of type 'BotwTrainer.ETCPGeckoException' was thrown.   at BotwTrainer.TCPGecko.Dump(UInt32 startdump, UInt32 enddump, Stream[] saveStream)
   at BotwTrainer.TCPGecko.peek(UInt32 address)
   at BotwTrainer.MainWindow.DebugData()

Speed Code
Exception of type 'BotwTrainer.ETCPGeckoException' was thrown.   at BotwTrainer.TCPGecko.Dump(UInt32 startdump, UInt32 enddump, Stream[] saveStream)
   at BotwTrainer.TCPGecko.peek(UInt32 address)
   at BotwTrainer.MainWindow.DebugData()

Weapon Slot Code
Exception of type 'BotwTrainer.ETCPGeckoException' was thrown.   at BotwTrainer.TCPGecko.Dump(UInt32 startdump, UInt32 enddump, Stream[] saveStream)
   at BotwTrainer.TCPGecko.peek(UInt32 address)
   at BotwTrainer.MainWindow.DebugData()

Bow Slot Code
Exception of type 'BotwTrainer.ETCPGeckoException' was thrown.   at BotwTrainer.TCPGecko.Dump(UInt32 startdump, UInt32 enddump, Stream[] saveStream)
   at BotwTrainer.TCPGecko.peek(UInt32 address)
   at BotwTrainer.MainWindow.DebugData()

Shield Slot Code
Exception of type 'BotwTrainer.ETCPGeckoException' was thrown.   at BotwTrainer.TCPGecko.Dump(UInt32 startdump, UInt32 enddump, Stream[] saveStream)
   at BotwTrainer.TCPGecko.peek(UInt32 address)
   at BotwTrainer.MainWindow.DebugData()

**Comment by rEd2k** [comment]
I have changed nothing since the screen shot I uploaded just so you know, also I figure what has made the edit on materials work properly now is since version 2.5 is that the changed values don't save on a global scale, I guess my real problems stem from only the codes on the code tab and how they are handled.

I think you already know all that though lol, but I wonder why they are so problematic then? Anyways, I will continue to test ;)

**Comment by joffnerd** [comment]
Can you test this please:

https://joffnerd.s3.amazonaws.com/app.publish.test.zip

**Comment by rEd2k** [comment]
Tried your newest release, got a game crash when trying one edit rupees, then tried again but with hearts and crashed again. Always only in the codes tab it crashes now, also, got no error in the error log both times :(

All I get is the on screen error of for both tries:

Illegal command byte received: 0x2a
Server Version: 02/25/2017

All other fixes still work and I found out that editing too many materials at once wont allow them to save, 
so editing in small batches are ok, plus maybe triggering some use of the materials (doesn't matter which one) and a fast travel all seem to make the values stick.

Simply doing an edit, save, then load, doesn't seem to always work for some reason and other times doing an edit, save, then load works just fine and saves the value, not a big deal just weird some times.

Really appreciate your hard work man, you really have come far very fast ;)

**Comment by joffnerd** [comment]
As far as I can tell its something to do with your wifi connection. Do you have wifi issues outside of this app?

I don't understand the deep underlying code enough to help i'm afraid :(

**Comment by rEd2k** [comment]
Wifi works great, I do have a complex home network though, but its never given me trouble. I don't see how the connection is always the problem. The other trainer from Shinzuya/GamePil can freeze the health and/or stamina no problem.

Are you using the same code for those values?

**Comment by rEd2k** [comment]
Testing your latest version atm... will report back.

**Comment by rEd2k** [comment]
I HAVE AN ANSWER FOR YOU, I FIGURED IT OUT AND YOUR TRAINER IS FINE!!!

The problem is THE NETWORK CARD!!

I disabled my 10gb NIC and used my 1gb nic instead and THE CODES TAB NOW WORKS PERFECTLY!

All Codes in the code tab are perfect and have no issue what so ever :))))

I have an intel 1gb nic and a Mellanox 10 gb card. There is a HUGE difference between them driver and hardware wise, so it all makes sense.

The only thing is I feel so bad putting you through so much uneeded debugging!!! IM SO SORRY FOR THAT!!!! :S 

Your trainer has always been great, I'm now going to call it AWESOME! This whole time it was my end wtf!

I will report anything unusual if I find anything. Thank you SO MUCH for your efforts! You deserve a pat on the back and beer good sir! :)

**Comment by rEd2k** [comment]
One odd thing I have noticed now that it works fine, when I click on the save tab, the button is slow to respond like there's a delay before the save button returns to the unclickable state it is when there are no changes to commit. It's like that every time I hit the save button now.

Before it was almost INSTANT when I had the 10gb nic in use, but now it almost seems to wait/take longer after every click I do on the the save button. That may have some indication as to why it would always fail before ;)

**Comment by joffnerd** [comment]
Awesome. Glad it's working for you :-) This is useful to know for others who have similar problems. So many factors with computing. 

So the save button seems slow because the app is 'busy' writing to the wii u and so it freezes while doing so. I should make it async really. It basically takes time for the data to be sent and written to memory so until that competes the button is frozen. When the action finally competes the button is then disabled so it is a very slow to respond feel about it. Thanks for persisting and using the trainer.

**Comment by rEd2k** [comment]
When I get time I'm going to see what network setting could be affecting me and share it with you. I'm sure I can get this working with my 10gb nic with enough playing around, while maybe also finding a common setting that can help others with their connection as well.

If I find out what could be a root cause for some/most people and how to correct it, I will close this thread. If I can't find the exact reason in a reasonable time I will still come back and close it, the issue is fixed for the most part for me, but I would like to try and help a little further for other people first if I can. 

Just a quick comment, I love how your trainer allows the stamina to be infinite but it doesn't show the ugly stamina circle/meter to do so, that's great ;) Oh and don't lock your rupees when talking to the large Fairies for the first time, the game will freeze lol. Stay awesome good sir, until next time....

**Comment by joffnerd** [comment]
Thanks dude, I think its just poor connection code that i borrowed. I may be way off but i think your 10gb nic is too quick and the Wii U can't cope with the overload due to my implementation. I plan to migrate it over to something cleaner reflecting JGecko U but they may take some time.

Just out of interest, can you connect to to a game with JGecko U with both your network cards?

**Comment by rEd2k** [comment]
So busy atm, but as soon as I get the chance I will try out JGecko U some time later today 😉

**Comment by rEd2k** [comment]
JGecko U connects just fine with either network card but I need to add some code(s) to try to see if it will actually work. Have any that work on JGecko U? I'm new to using it and played with it before but never really got into it, I have to figure out where to enter the code properly lol :P

**Comment by Boldboro** [comment]
Can someone please explain what I am supposed to disable and enable to get this to work for me.
I don't know much on network cards or how they even work.

**Comment by JellyBelly12346** [comment]
Un-Equip everything and then pause your game.

**Comment by JellyBelly12346** [comment]
If its both the trainer and the game, you should get a fw.img file and use the CFW booter from the homebew store, launch that then load the homebrew launcher from sthetix.info/wiiu rather than Loadiine. Boot into the CW Launcher, then after you load that then go back to sthetix.info/wiiu and install TCPgecko then open Zelda. Should work there.

**Comment by Boldboro** [comment]
Unequipping didn't fix my error.

**Comment by rEd2k** [comment]
@Bolboro I haven't disabled anything on my intel network card but it works using that card with no crashes at all now. My problem was that I was using a 10gb network card (which I have now disabled/stopped using), it's 10x the speed of regular networking adapters and has different drivers that run it with a ton of totally different settings and features which all contributed to my crashing.

Joffnerd thinks that the raw speed of my 10gb network card was causing my issues as the wii u probably couldn't keep up, or at least the networking code for either TCPGecko or the trainer itself couldn't keep up. In any case switching to a standard, decent quality networking car (in my case an intel) seems to have fixed the issues that were plaguing me.

I'm right now in the process of trying to figure out if I can still use my other faster 10gb networking card with different settings instead, and they may be common settings that other networking cards share. I'm hoping to solve the problem a lot of people are having with a simple networking tweak. No idea if it will work and so far I haven't had any luck. I will post my findings if I do ever get it to work, but don't hold your breath lol.

I have a feeling that generic networking cards that are built into most systems that are not an intel may have the same issue as my 10gb one did as they are off the beaten path so to speak in terms of quality and compatibility (except my 10gb card it's just waaay different I think, cuz it's great quality).

**Comment by Boldboro** [comment]
So there's absolutely no way I can use this trainer whatsoever is what you're saying unless I buy a new network card for my laptop...

**Comment by joffnerd** [comment]
I honestly don't know. As I keep saying, it could be one of so many things.

Is your AV running?
Did you update your version of .NET?
Have you used the latest code handler?

Outside of this I can't help, i'm sorry. I'm not a professional developer, just doing in this in my spare time and learning as I go.

**Comment by Boldboro** [comment]
I have no Antivirus at all.
My .NET is 4.0 I think. How do I check? Do I need one that's better?
I use the codehandler that came from the Gecko U Updater.

**Comment by joffnerd** [comment]
It's in the readme

**Comment by Boldboro** [comment]
I have not seen a readme in the files I've downloaded.

**Comment by Boldboro** [comment]
http://oi63.tinypic.com/otpu84.jpg

**Comment by joffnerd** [comment]
Sorry man but something about your setup doesn't work.

**Comment by Boldboro** [comment]
What's not fair is that everone else can get it to work and not me and can't seem to either find a solution or at least help me figure out how to do the same thing in this trainer through the memory viewer of JGecko U.
I just want to edit as well and seems like because others got it to work they don't care to try and help someone to get the same benefits as them.

I also don't know what "setup" I need as I'm not doing anything different than anyone else to try and simply get this to work.

**Comment by rEd2k** [comment]
@Boldboro Don't sweat it too much man, the truth is that all trainers that are out there for Zelda BoTW are kinda flakey at this stage. They are so new that they have issues, but the creators are working hard to try and make them more compatible and work for everyone. Joffnerd doesn't have extensive knowledge of the network code used to make his trainer super uber compatible with everyone's setup. 

Just look at what I went through, I am still testing his trainer even though I got LUCKY and got it to work with a different network card. That's all, I did everything else under the sun to get it to work before and had no luck also. I had to use Jofferd's trainer and the other popular trainer out there to get anywhere in combination. I would edit weapons with Joffnerds trainer and use the stamina code and inf health with another and after an edit, I was always disconnecting and reconnecting between them. 

If Joffnerd or any other coder went ahead and made the network code and trainer all together from the ground up I'm sure he could help you better... Just don't feel like no one is helping you bud, cuz there are a lot of others in your boat, the hacks just aren't that mature and may never be, there's no way to know since these things as they take time and they are done for FREE and are just personal projects. If you want to help to speed up the fixes and progress then beta test like I did, and with enough playing around you may also find a fix that works for you. 

I'm not some uber amazing programmer or anything, I just have general computer knowledge that gets me by when it comes to this stuff, it helps a lot if you want to make things work... it's computers after all, not a game console, it's not always 1-2-3 and you need to be patient and bang away at the problem until you can find a fix or workaround, that's just how these things go. That's how I did it, that's how anyone should do it, instead of calling it unfair -work the problem, learn and contribute and then maybe you will get somewhere ;)

**Comment by rEd2k** [comment]
@Joffnerd  I have been testing all of your releases up to 3.1 as of present and everything is going fine and all codes are working as you add them. I am of course having no luck on finding a network tweak or setting that may allow others to use the trainer when using a different network card like my 10gb one. 

I am about to try the latest trainer on my simple file server as it's always on and it's best I run your trainer(s) from that machine, and that machine has a simple crappy realtek NIC in it. I am wondering what will happen over there, it also has the EXACT SAME 10gb nic as my main machine and I will be trying again with that one as well just to see what happens. I will report back as soon as that's tested ;)

**Comment by Boldboro** [comment]
@rEd2k 
There's more than one other than breath.exe? The creator of breath.exe stopped working on it long ago. What othet BotW Trainers are out there as I just want to modify a few things. That's all.
Breath.exe never failed me and I use that for my codes like moonjump and such. I just want an item editor.

**Comment by rEd2k** [comment]
@ Boldboro

> How do I tell what is my network card so I can see if Windows 8 can update the drivers?

You tube bud.... you tube.

> I can't use wired as my modem is far away from me....

If you want to try and solve the problem you have to at least try and test with using your ethernet/wired connection and since it is a DIFFERENT NETWORKING CARD that you would be using for that type of connection, chances are it might actually work for you, like it did for ME by CHANGING THE NETWORK CARD USED. Wifi is a networking connection just like an ethernet port is and this means it is considered a network card/interface just like the wired kind everyone uses, it's just that its wiresless <-(which could be the root of your problem).

> I don't think I ever seen an ethernet port on my Wii U before.

That's right, the wii u doesn't have a wired connection, hence why I stated previously to at least WIRE THE COMPUTER to a wireless router to eliminate potential problems. The Wii U will have to be wireless, you can't get away from that unless you buy a usb to ethernet adapter specifically made for the Wii U, but it's not needed.

Unless you have a computer tower or a huge beast of a machine that you cannot move close to a router for a wired connection, there's no reason you can't take a laptop over to your router and run the trainer on a wired connection just for a simple test. Also don't forget to TURN OFF YOU WIFI on the computer your testing with to MAKE SURE you are using the WIRED connection to the router. 

Once you get everything up and running, try a stamina or health cheat code and then go back to the game and see if your invincible now or can run forever. If it failed you will  get an error right away and then you know it didn't fix the problem and you may have to look for another solution. Good luck!

**Comment by rEd2k** [comment]
I would just like to add that I just tried your latest version of the trainer (3.6.1) and it totally fixes ALL and ANY of the issues discussed previously and works perfectly with ALL of my various network cards/interfaces now despite what driver version they use. GREAT JOB JOFFNERD! :) Thank you AGAIN for your amazing talent and hard work on this. Your trainer was already great, but you have made it the BEST trainer I have the pleasure to use for one of my now favorite games. You rock bud, we are so lucky to have some one like you! :) ;) XD
