### ISSUE TITLE
Maser sword Charge or glow crashes

### ISSUE THREAD

**Issue by zm1868179** [joffnerd/botw-trainer#172]
Using either the Master sword charge or glow on the US Version of BOTW causes a hard crashes there is no exception on screen

**Comment by skoolzout1** [comment]
What version of BoTW are you using?

**Comment by zm1868179** [comment]
Version 4.1.5 my wii u is on a separate network with no internet so it doesn't have the latest botw update installed so I can still use the 4.1.5 version

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
