### ISSUE TITLE
BoTW Trainer Crashes on connect

### ISSUE THREAD

**Issue by redtitanjr** [joffnerd/botw-trainer#175]
After updating the trainer and changing my TCPGecko to the most recent one (with codehandler installed) and messing around a bit on BoTW with the J gecko U trainer, I decided to switch back to the BOTW Trainer, which ends up immediately crashing my Wii U. I have no idea what the issue is, I'm running BoTW with the latest updates, and I have the latest trainer

**Comment by redtitanjr** [comment]
PS
I also have the DLC Ver 2.0

Not sure if it matters tho

**Comment by Hyram1** [comment]
I have the same problem

**Comment by plague17** [comment]
Same here :( I hope this gets fixed soon

**Comment by plague17** [comment]
I have a question redtitanj, how did you get J gecko U working? I can't seem to...

**Comment by Targren** [comment]
This is really strange. I just tested it and can't reproduce it. 

Zelda 1.3.1 + DLC 2.0 
WiiU 5.5.1 
Haxchi 
Freshly downloaded 4.1.6 trainer

It looks like TCPGecko hasn't been updated in yonks, so it seems unlikely that the problem is any change there...

**Comment by plague17** [comment]
I'm on 5.5.2 though

**Comment by skoolzout1** [comment]
Well i know someone with 5.5.2, uses Haxchi and it works for them without crashes.

Are any of you PAL users?

(from Europe or Japan?)

**Comment by RexNihil** [comment]
I've gotten JgeckoU to work on 5.5.2, but I have to reinstall tcpGecko every time.

Also the only code I can get to work is the infinite Amiibo uses, which granted is super handy, I really wanted infinite stamina.

I like climbing shit.

Breath connects but doesn't work, and BotW trainer won't even connect.

**Comment by RexNihil** [comment]
Red, I had something like this happen, but I forgot to disconnect one before I tried to connect with the other, so it black screened.

**Comment by hyruleherb** [comment]
Hey guys I did a bit of digging around and found the solution to the problem. The TCPgecko.elf file (for whatever reason) fucks with the trainer and causes an instant crash. Using this custom TCPgecko.elf file (which i found on gbtatemp) it comepletely fixes the problem. Hope it works for you guys!

https://github.com/BullyWiiPlaza/tcpgecko/raw/f42bf358e891e7e53e5577c668958233a547ef6d/tcpgecko.elf

Here's my setup information for anyone wondering.
BOTW: 1.3.1 (v122)
BOTWDLC: 2,0
Trainer: 4.1.6
Haxchi
WII U 5.5.1 (also works on 5.5.1)

**Comment by plague17** [comment]
Thank you so much! It works perfectly!

**Comment by Eurodrome** [comment]
I have Zelda BOTW version 1.3.3

Since yesterday the game crashes on connect. The day before everything worked perfectly.

**Comment by Targren** [comment]
@Eurodrome 

The update just came out and the trainer hasn't been updated to 1.3.3 yet.  

The main page tells you in very large letters that it requires version 1.3.1. You'll have to wait for an update.

**Comment by Eurodrome** [comment]
@Targren 

Yes i know. Thnx for the reply.
