### ISSUE TITLE
Needs an update!

### ISSUE THREAD

**Issue by GoodP** [joffnerd/botw-trainer#178]
Zelda BOTW 1.3.3 has came up! The trainer here don't work on the update. Please update! Thanks for the nice app!

**Comment by Shaza1991** [comment]
Yes I agree please update this app and how long will it take

**Comment by RoyTerrazas** [comment]
also the dlc are coming too, it just goes crazy when trying to run under the dlc

**Comment by Papakuma91** [comment]
hello world,

we need an update for this fantastic trainer please !! thx in advance !

**Comment by aybabtu123** [comment]
Stop. It does not make sense to update this until after DLC 2 is released at the earliest. It would be a waste of time otherwise. Look into save game editors.

**Comment by skoolzout1** [comment]
Well I've put the time into updating most of the codes used by this trainer. But someone else who knows how, has to add them into the trainer.

**Comment by rabbitt** [comment]
@skoolzout1 any chance you might be able to post them somewhere? I might be able to put a PR together to add your updated codes. 

P.s. out of curiosity, are they for 1.3.3 or 1.3.4 ?

**Comment by joffnerd** [comment]
https://pastebin.com/GhVJX4ZY

**Comment by skoolzout1** [comment]
Not all the codes are there. The horse codes are missing. I'm out of town for a week so I can't do anything further. I can provide assistance explaining anything regarding my codes but that's about it.

**Comment by Papakuma91** [comment]
i dont understand how u made it for this trainer working with an update ? or Not ? thx

**Comment by subworx** [comment]
@skoolzout1 any chance of seeing the 1.4.0 codes soon, please?
I am trying to figure out how to update the trainer myself so at least the basics work.

**Comment by Mr-Rixa** [comment]
@skoolzout1 updated his pastebin! 1.4.0 codes [there](https://pastebin.com/GhVJX4ZY)

> Last Edit: December 13th - 2017: All 1.4.0 Codes now posted!

**Comment by Davillion11** [comment]
Well, 1.4.1 is now out, thanks for putting time into creating this great trainer and for all of the updates for it too, it's much appreciated :+1:  :100:
