### ISSUE TITLE
Item Change Bug

### ISSUE THREAD

**Issue by AquaSize** [joffnerd/botw-trainer#18]
I gave me an Key Item, but it's now in the Sword Kategorie? And when I give me a Sword it's in the Key Item Kategorie?

**Comment by joffnerd** [comment]
You can change the page an item is on but you would have to do it via JGecko U

**Comment by AquaSize** [comment]
What you mean by this? You mean the other Trainer or what?

**Comment by joffnerd** [comment]
This sounds like the usual refresh bug where things moved and you overwrote them. Load an older save  and  refresh often especially before you save items. Check GBA Temp for others who have  done  the same
