### ISSUE TITLE
Needs Update!!!

### ISSUE THREAD

**Issue by Huskyk91705** [joffnerd/botw-trainer#180]
It crashes the game on v.1.3.3 and v1.4 Please fix!!!!

**Comment by joffnerd** [comment]
I don't have time, sorry

**Comment by Zanza25** [comment]
do you think you will do during the next month? or  will you leave the program

btw, thanks for you work even if you don't give updates, we at least should thank you

**Comment by neosonic2k** [comment]
Champion’s Ballad is out! Happy Holidays! Thanks for your work!
