### ISSUE TITLE
no longer working

### ISSUE THREAD

**Issue by OutlawPinky** [joffnerd/botw-trainer#182]
my game updated overnight and now the trainer doesn't work do you have an ETA for the next update to the trainer?

**Comment by wiiu-hacker** [comment]
If you have 1.3.4 use jgecko u instead.  It works.  The codes are working and available by skoolzout.

**Comment by OutlawPinky** [comment]
where can I find those codes? I searched for skoolzout and couldn't find anything

**Comment by rabbitt** [comment]
@OutlawPinky see: [issue #178](https://github.com/joffnerd/botw-trainer/issues/178#issuecomment-347998401)

**Comment by franikooo** [comment]
hi my version is 1.4.0 too can you do something? and an updated trainer? It's European version

**Comment by rabbitt** [comment]
It's important to remember that the people who are kind enough to work on these projects have real lives outside of these projects; more importantly, they do not make any money from these projects and therefore have little incentive - outside of passion, curiosity, and the occasional compliment - to continue them. Just hang tight and I'm sure that someone will update the codes sometime soon. 😄
