### ISSUE TITLE
DLC 2! Please update!! Thanks!

### ISSUE THREAD

**Issue by GoodP** [joffnerd/botw-trainer#183]

**Comment by micha1987** [comment]
You can use this :

http://www.marcrobledo.com/savegame-editors/zelda-botw/

**Comment by Carone90** [comment]
@micha1987

Isn't marcrobledo's savegame editor botw only for Cemu?

**Comment by micha1987** [comment]
No, you can also use this for the wii u. But u must dump your savegame.

**Comment by rabbitt** [comment]
@Carone90 Nope, it works with your garden variety Wii U as well - though, you have to be able to get a dump of your savegame (using something like SaveMii, a homebrew app).

**Comment by Carone90** [comment]
Oh ok thanks

**Comment by franikooo** [comment]
How to use

**Comment by micha1987** [comment]
There is at least one video on YouTube. ;)

**Comment by franikooo** [comment]
I have a problem when making a backup of my botw game, it says "backup failed DO NOT restore from this slot." I have tried several slots and he will not let me either. The savedata is saved in usb. Can anybody help me?

**Comment by micha1987** [comment]
I have no Problem with that.

You can also try Savemii Mod.
