### ISSUE TITLE
Cant connect

### ISSUE THREAD

**Issue by MintCrystal556** [joffnerd/botw-trainer#185]
when i try to do it with load buffer enabled i get (on my wii u)
exception dsi occoured
*shitload of numbers*
when i try it with load buffer disabled i get this error (on my pc) and nothing happens on my wii u 
Error data will appear here
Connection closed.   bij BotwTrainer.TcpConn.Read(Byte[] buffer, UInt32 nobytes, UInt32& bytesRead)
   bij BotwTrainer.Gecko.GetServerStatus()
   bij BotwTrainer.MainWindow.ConnectClick(Object sender, RoutedEventArgs e)
edit: when i try it with buffer enabled i get this error on my pc 
Error data will appear here
Connection closed.   bij BotwTrainer.TcpConn.Read(Byte[] buffer, UInt32 nobytes, UInt32& bytesRead)
   bij BotwTrainer.Gecko.ReadBytes(UInt32 address, UInt32 length)

**Comment by piratesephiroth** [comment]
As you can see, this project was last updated october 30 therefore it's not compatible with the latest update of the game.

**Comment by MintCrystal556** [comment]
Oh, i didnt see that coming. is there a fork or an alternative to this tool that does work on the latest version?

**Comment by meanwolf99** [comment]
As soon as he updated this i powered up my wiiU to find a cracked gamepad screen
