### ISSUE TITLE
Items not loading

### ISSUE THREAD

**Issue by jozzeed** [joffnerd/botw-trainer#187]
Hi i tried the new trainer update and got to a problem. I can connect to my console but when i hit load items, nothing is showing up. I tried to refresh and play around in the code and nothing seems to work. Thanks !
![capture](https://user-images.githubusercontent.com/33524683/34495374-e2d47604-efc2-11e7-9854-3f23ab6c1747.PNG)

**Comment by sonicwolfsdutch** [comment]
same issue and i had to connect twice only time and coordinates works for me i updated tcpgecko and codehandler running on pal version and firmware 5.5.2

**Comment by Davillion11** [comment]
I Also Have The Same Issue As Well

**Comment by Shaza1991** [comment]
same here

**Comment by Shaza1991** [comment]
also need more working codes

**Comment by gathered9** [comment]
Same issue. Able to change time and load coord but can not load items and total items always read as 0. I have tried refreshing after save, load, and restart. Also cheats do not work, tried moonwalk and was unable to get it to work,

**Comment by joffnerd** [comment]
The codes part is down to you, i just supplied a demo codes file

I don't have 5.5.2 so can't help there, sorry

**Comment by jecoconono** [comment]
Hrm teleportation and time setting already works so I doubt it has to do with 5.5.2...

**Comment by joffnerd** [comment]
Might be DLC, update coming

**Comment by sonicwolfsdutch** [comment]
eyy codes works on 5.5.2 with dlc just letting you know

**Comment by AnimeLove** [comment]
Game version?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ThisLegitYT** [comment]
You have to wait a few minutes after loading the game and then click the load items button. If that doesn't work you may need to get the DLC which fixed it for me.
