### ISSUE TITLE
NO items loading

### ISSUE THREAD

**Issue by ashieo1130** [joffnerd/botw-trainer#189]
Hey! I love the botw trainer and was excited for the new update to come out. I tried to connect it to the trainer and there are no items and seems so crash my wii after about 30 seconds of connection. I am running u.s. firmware 5.5.2 and game version 1.3.4 . I am not very good at coding so you will have to explain it well (sorry bout that ☹️ just not good at coding) And thank you in advance!

**Comment by micha1987** [comment]
Look at the readme: 

Legend of Zelda: Breath of The Wild Trainer

Version Of The Game Needed: 1.4.1

Only tested on 5.5.0 firmware

**Comment by ashieo1130** [comment]
@micha1987 I have like no more space on my wii u left do I have not been able to update Breath of the WIld.  THanks for answering! Also, I beleive you were the one who told me about this ( I might be wring tho) http://www.marcrobledo.com/savegame-editors/zelda-botw/ and its amazing!

**Comment by ThisLegitYT** [comment]
If no items are loading and you are on version 1.3.4, all you need to do is open your save file like normal and wait a minute, then click load items
