### ISSUE TITLE
"something went wrong" error

### ISSUE THREAD

**Issue by WiseHorror** [joffnerd/botw-trainer#19]
I keep having this problem, I connect to my Wii U's local IP and when I try to Load, the trainer just returns an error messages saying "something went wrong"

I have the latest TCP Gecko, Breath of the Wild PAL v33 with DLC, running Mocha CFW.
What could be the issue?

**Comment by joffnerd** [comment]
Are you using Bullys tcp gecko?

**Comment by WiseHorror** [comment]
Yes I am, should I not use that one?

**Comment by joffnerd** [comment]
Yes just checking. the latest version logs some data to a new Error Tab.

**Comment by WiseHorror** [comment]
So do I send you an error log file or something? I don't know where it's located if it exists

**Comment by joffnerd** [comment]
You need to use bullys tcpgecko.

I added more data to error tab so just post it here if you like

**Comment by WiseHorror** [comment]
I can't access tabs when it gives me the error. It simply gives the error and the tabs are greyed out, Only thing I can do is close the program.

**Comment by joffnerd** [comment]
New version which should help identify where exactly this happens

**Comment by joffnerd** [comment]
Can you test this please:
https://joffnerd.s3.amazonaws.com/app.publish.test.zip

**Comment by WiseHorror** [comment]
Sure, sorry for the long wait, I was busy irl.

**Comment by WiseHorror** [comment]
This is what it says in the error tab:

`Path returned multiple tokens.   at Newtonsoft.Json.Linq.JToken.SelectToken(String path, Boolean errorWhenNoMatch)
   at BotwTrainer.MainWindow.GetNameFromId(String id, String pagename)
   at BotwTrainer.MainWindow.LoadDataAsync()`

**Comment by joffnerd** [comment]
Looks like a duplicate item in the json, 

This version should log what item is it https://joffnerd.s3.amazonaws.com/app.publish.zip

**Comment by WiseHorror** [comment]
It shows this:

`The calling thread cannot access this object because a different thread owns it.   at System.Windows.Threading.Dispatcher.VerifyAccess()
   at System.Windows.Threading.Dispatcher.DisableProcessing()
   at System.Windows.Documents.TextContainer.BeginChange(Boolean undo)
   at System.Windows.Documents.TextElementCollection`1.Add(TextElementType item)
   at BotwTrainer.MainWindow.LogError(Exception ex, String more)
   at BotwTrainer.MainWindow.GetNameFromId(String id, String pagename)
   at BotwTrainer.MainWindow.LoadDataAsync()`

**Comment by joffnerd** [comment]
Hah yeah, hard to test when its someone else's machine

https://joffnerd.s3.amazonaws.com/app.publish.1.zip

How about that one?

**Comment by WiseHorror** [comment]
Now it just keeps giving me a message saying "problem with weapons" over and over, I click OK and it just pops up again

**Comment by joffnerd** [comment]
You have an empty item somehow, did you save with an empty textbox?

https://joffnerd.s3.amazonaws.com/app.publish.2.zip

**Comment by WiseHorror** [comment]
Not sure what you mean by saving with an empty textbox...
Anyway I tried that one and now it gives me another endless pop up error box saying `Problem with " '0'`

**Comment by joffnerd** [comment]
Added a new  version here, something is weird with your items. This should report the memory address its trying to read. Can you check it out in jgecko u.

https://github.com/joffnerd/botw-trainer/releases/tag/v2.5.6

**Comment by WiseHorror** [comment]
I can't connect JGecko U, for some reason it just crashes and shows Exception type DSI occurred! with a bunch of memory addresses and stack dumps

**Comment by joffnerd** [comment]
Yeah so something isn't setup correctly with your WIi U / Tcp Gecko etc

Its not related to the trainer i'm afraid. If you get jgecko u working then this will work, i'm fairly sure

**Comment by WiseHorror** [comment]
For some reason it works if I use the TCP Gecko hosted at loadiine.ovh, but when I use the Homebrew Channel version it doesn't work. Weird.

**Comment by joffnerd** [comment]
You need to use the version that this gets really:

https://github.com/BullyWiiPlaza/Gecko-U-Updater

Also I don't have  DLC so maybe this messes all the codes up

**Comment by WiseHorror** [comment]
DLC shouldn't be the problem, As I said, it works fine with loadiine.ovh's TCP Gecko. Also, I did download TCP Gecko through that updater. It still doesn't work.

**Comment by joffnerd** [comment]
DLC might shift where items are  stored just like when v16 was replaced by v33 which im pretty sure is the issue since your data is blank

**Comment by joffnerd** [comment]
Yeah i don't fully understand. There are various versions of Tcp Gecko floating around and they must have  differences.

**Comment by joffnerd** [comment]
Closing this as its changed a lot since the issue was raised
