### ISSUE TITLE
It says unable to connect.

### ISSUE THREAD

**Issue by Fireflaker** [joffnerd/botw-trainer#190]
The program is run as administrator and all anti-virus software have been shut down.

**Comment by Fireflaker** [comment]
Game version: 1.3.0
Cemu version: 1.9.0+Cemu hook

**Comment by micha1987** [comment]
Legend of Zelda: Breath of The Wild Trainer

Version Of The Game Needed: 1.4.1

Only tested on 5.5.0 firmware

**Comment by Fireflaker** [comment]
Understood. Thank you.
