### ISSUE TITLE
My items won't load...

### ISSUE THREAD

**Issue by RivoxYT** [joffnerd/botw-trainer#192]
Hello so i used to use your trainer before the update and it worked perfectly, but then i stopped play BOTW for a while when i got back and downloaded the new update and trainer i connected to my wii u with TCP and ip and when i clicked load items it would load instantly with no items and show this.

![image](https://user-images.githubusercontent.com/35233464/34684473-d013d59e-f46a-11e7-9dd6-dc9729d0bbd0.png)

I'm using 5.5.2 please help.

**Comment by DMartelly** [comment]
Which game version are you running?

It should be version 1.4.1

**Comment by RivoxYT** [comment]
yeah ver 1.4.1

**Comment by sonicwolfsdutch** [comment]
did you update codehandeler and tcpgecko? it works on my end

**Comment by DMartelly** [comment]
I'm not sure how to help.

I am currently running version 1.4.1 with DLCs and firmware 5.5.2. no problems on my end.

You can try to roll back to release 4.2.2. this is the release I have and it is working fine currently.

**Comment by RivoxYT** [comment]
i've updated tcp gecko but i don't think ive updated code handler what ver is the code handler now?

drop a link if possible..

**Comment by sonicwolfsdutch** [comment]
https://github.com/CosmoCortney/PPC-Cheat-Code-Handler/blob/master/codehandler.bin

**Comment by RivoxYT** [comment]
ok i dragged it to where i have tcp on my wii u. do i do install with built in code handler or with sd cheats and code handller?

**Comment by Shaza1991** [comment]
Hey is it possible that someone can fix the fast run option and the moon jump option in the cheats menu they don't work

**Comment by RivoxYT** [comment]
@Shaza1991 it says hold zr but un equip your sword and hold r... thats how i figured it out

**Comment by Shaza1991** [comment]
OK I'll give it a try thanks

**Comment by Shaza1991** [comment]
Does that also work with the moon jump

**Comment by Shaza1991** [comment]
That method doesn't work for me

**Comment by RivoxYT** [comment]
ok guys i dont know how i fixed it but i did im cosing this issue nw bye
