### ISSUE TITLE
no longer works with pro controller

### ISSUE THREAD

**Issue by thelordisarceus** [joffnerd/botw-trainer#195]
Hey, i just downloaded the new version and realized the pro controller feature is gone, my gamepad can't hold a charge and i was hoping you might be able to fix this.

Thank you.

**Comment by thelordisarceus** [comment]
Also the run fast code does not work at all.

**Comment by Shaza1991** [comment]
It does if you use the Wii U gamepad itself

**Comment by mudwaster** [comment]
@thelordisarceus check this...https://gbatemp.net/threads/botw-item-names-for-pandaonsmacks-trainer.463959/page-66
