### ISSUE TITLE
Items not loading in my inventory

### ISSUE THREAD

**Issue by Judeisawesome** [joffnerd/botw-trainer#197]
When I press the "Load Items" button, my inventory won't show up. How do I fix this?

**Comment by AnimeLove** [comment]
Version?

**Comment by jdeknoblo** [comment]
I have the same problem, im on 5.5.2 and the newest version of botw

**Comment by Judeisawesome** [comment]
5.5.2

**Comment by AnimeLove** [comment]
![unbenannt](https://user-images.githubusercontent.com/35126975/36057020-dd3aa884-0e09-11e8-94c0-b55326e9057d.PNG)

**Comment by Judeisawesome** [comment]
how do I downgrade ???

**Comment by jdeknoblo** [comment]
when i downgrade its impossible to play because my wii u forces me to update the game

**Comment by Judeisawesome** [comment]
that sux ass

**Comment by Shaza1991** [comment]
Downgrade to 5.5.1 and when it asks you to update the game then use haxchi if you have hacked your device with that then launch NNU-Patcher then the next time you start your game and it asks to update the game the game should automatically update without asking to update your firmware

**Comment by Judeisawesome** [comment]
@Shaza1991 how do I downgrade my wii u? (I just started to hack my wii u so I will be bad at things.)

**Comment by Shaza1991** [comment]
Don't worry about downgrading how do you intend on hacking your device

**Comment by Shaza1991** [comment]
https://www.reddit.com/r/WiiUHacks/comments/6u9f8j/tutorial_how_to_install_haxchi_on_wii_u_552/

**Comment by AnimeLove** [comment]
![win_20180210_16_02_50_pro](https://user-images.githubusercontent.com/35126975/36063336-f6b39204-0e7b-11e8-8ab2-af6898b89f93.jpg)
install CFW it solves all ya Problems

**Comment by Judeisawesome** [comment]
@AnimeLove do I use Mocha CFW?

**Comment by AnimeLove** [comment]
found a way

1.
Download FTP Everywhere (or somthin like this)
2.
open storage_slc/security/versions.bin with hex editor
3.
search for BOTW title ID (00050000101c9500)
4.
change it to 00050000101c0000
5.
safe and replace with ftp client
6.
 donwload and install older Update via WiiUUsbHelper and WupInstaller
7.
restart
8.
enjoy

**Comment by Judeisawesome** [comment]
@AnimeLove could I brick my console?

**Comment by AnimeLove** [comment]
Dump your Nand to be safe but it should not brick it

**Comment by Judeisawesome** [comment]
idk how to dump so I will just do it

**Comment by AnimeLove** [comment]
![win_20180210_19_26_45_pro](https://user-images.githubusercontent.com/35126975/36065255-7d408630-0e98-11e8-9935-91dcd1edd921.jpg)
works fine

**Comment by Judeisawesome** [comment]
okay. I am new to this stuff so i will ask a LOT of questions.

**Comment by Judeisawesome** [comment]
sorry

**Comment by Judeisawesome** [comment]
wait, how do I get Hex Editor?

**Comment by Judeisawesome** [comment]
oh it is working

**Comment by Judeisawesome** [comment]
but it says there was an error with the file so I could not open it


https://gyazo.com/e3f0ff9f82e69063cdcf8f9281a048b4

**Comment by Judeisawesome** [comment]
@AnimeLove https://gyazo.com/e3f0ff9f82e69063cdcf8f9281a048b4


wut

**Comment by AnimeLove** [comment]
U need CFW (just use  CooldBootHax or Mocha) 
(CooldBootHax boots cfw automaticaly with your WiiU and Mocha u need to run after every restart)

**Comment by Judeisawesome** [comment]
@AnimeLove what do i use to open up Versions.bin

**Comment by AnimeLove** [comment]
Use Mocca (U need CFW only for Running FTPiiUEverywhere) just search in HB AppStore in Category Tools

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Judeisawesome** [comment]
@AnimeLove I did

**Comment by AnimeLove** [comment]
Does it work now?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Judeisawesome** [comment]
yeah but how do I edit Version.bin

**Comment by AnimeLove** [comment]
I used DFHEXEditor

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Judeisawesome** [comment]
@AnimeLove can you send me a link where t get it

**Comment by AnimeLove** [comment]
http://www.del-net.com/frmDFHEXEditorE.html

**Comment by Judeisawesome** [comment]
@AnimeLove where do I get older updates for BOTW

**Comment by AnimeLove** [comment]
Download them with WiiU USBhelper and install them with WupInstaller 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Judeisawesome** [comment]
kk

**Comment by Judeisawesome** [comment]
@AnimeLove how do I get title for WiiU Usbhelper

**Comment by AnimeLove** [comment]
👌

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Judeisawesome** [comment]
@Animelove ;-;

**Comment by AnimeLove** [comment]
What?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Judeisawesome** [comment]
@AnimeLove

How do I get the older BOTW Title

**Comment by AnimeLove** [comment]
![GitHawk Upload by AnimeLove](https://i.imgur.com/Z3J4GhJ.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Judeisawesome** [comment]
@AnimeLove hmmm... lemme guess, Wup Installer GX2?

**Comment by AnimeLove** [comment]
Yeah
And block Updates With DNS this stops only BOTW from detecting that u have to update... 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Judeisawesome** [comment]
@AnimeLove I already had the dns set to not auto obtain

**Comment by AnimeLove** [comment]
Ok 👌

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Judeisawesome** [comment]
@AnimeLove in the version.bin this is what happens

https://gyazo.com/ba2e0649ced4b3099b66eee758494d63

**Comment by Judeisawesome** [comment]
@AnimeLove in the hex editor, the version.bat is empty.

**Comment by AnimeLove** [comment]
It shouldn’t be empty 🤔

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Judeisawesome** [comment]
weird

**Comment by AnimeLove** [comment]
![GitHawk Upload by AnimeLove](https://i.imgur.com/OO26OSA.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Judeisawesome** [comment]
::::<<<<<<<<<<<<<<,,

**Comment by AnimeLove** [comment]
It would be helpful if you would make a video of anything your doing so I probably can spot the problem 🤔

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Judeisawesome** [comment]
kk, I will record a video on yt

**Comment by AnimeLove** [comment]
Thanks 👌

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by AnimeLove** [comment]
Too xD

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Judeisawesome** [comment]
waiting while choking on dr.pepper

**Comment by AnimeLove** [comment]
Nize

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Judeisawesome** [comment]
here is the vid
https://mega.nz/#!2JgmyRJK!Frg5lWfxB92hXbrmMFwpDs4sXp6g2LKQVeROHEqqaz8

**Comment by AnimeLove** [comment]
I think you should try downloading it again

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Judeisawesome** [comment]
kk

**Comment by Judeisawesome** [comment]
should I use the same installer or download a new one?

**Comment by AnimeLove** [comment]
https://mega.nz/#!vBVAjQxR Works fine for me

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by AnimeLove** [comment]
no mocha should be fine

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Judeisawesome** [comment]
I need decryption key to download

**Comment by Judeisawesome** [comment]
;-;

**Comment by AnimeLove** [comment]
I could Send u mine but it will be very risky

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Judeisawesome** [comment]
why?

**Comment by AnimeLove** [comment]
Because we don’t know what could happen to games installed on your wii

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Judeisawesome** [comment]
hmmmm

**Comment by Judeisawesome** [comment]
do I need to buy the decryption key?

**Comment by AnimeLove** [comment]
? Whut

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Judeisawesome** [comment]
https://gyazo.com/c0fe9f8c238b244792cc7184d37aed76

**Comment by AnimeLove** [comment]
Oh lol
https://mega.nz/#!bMkRmKyS!X2YLXAwWEq1pkoNE46-6tMmOadkrp-ZJ4X9Z2tNFKD4

That’s the version.bin of mine


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Judeisawesome** [comment]
could it break because I bought the US wii u?

**Comment by AnimeLove** [comment]
Oh forgot that 🤔 i have EU Codes 
Dont use it 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Judeisawesome** [comment]
should I reinstall the hex editor

**Comment by AnimeLove** [comment]
Had an idea

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Judeisawesome** [comment]
kk

**Comment by Judeisawesome** [comment]
Its cool talking to a non us person.

**Comment by AnimeLove** [comment]
Why? 🌚

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Judeisawesome** [comment]
all my friends are from the us. It's nice talking to someone different

**Comment by AnimeLove** [comment]
Yeah ur right

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Judeisawesome** [comment]
you here?

**Comment by AnimeLove** [comment]
Jo

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by AnimeLove** [comment]
Does it work?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Judeisawesome** [comment]
what work?

**Comment by AnimeLove** [comment]
Downgrading BOTW

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Judeisawesome** [comment]
lol I forgot lemme try

**Comment by Judeisawesome** [comment]
ugh my wii u auto shut off

**Comment by AnimeLove** [comment]
xD

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Judeisawesome** [comment]
would notepad++ work for the version.bin

**Comment by Judeisawesome** [comment]
OMG

**Comment by AnimeLove** [comment]
![GitHawk Upload by AnimeLove](https://i.imgur.com/6u2Sgtg.jpg]

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Judeisawesome** [comment]
I found out that I just needed to use HxD Hex Editor

**Comment by Judeisawesome** [comment]
how do I find the us copy for botw?

**Comment by AnimeLove** [comment]
https://mega.nz/#!qQdhmJLC!avZbl3XenXIfcWOEe1KKwpYdcd0IDWLK8pu9CZTTbr0 here a version.bin with just modified BOTW

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Judeisawesome** [comment]
is it usa copy??

**Comment by Judeisawesome** [comment]
sorry for wasting you time

**Comment by Judeisawesome** [comment]
just for downgrading botw

**Comment by AnimeLove** [comment]
Doesn’t matter🤷‍♂️

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Judeisawesome** [comment]
hello??

**Comment by AnimeLove** [comment]
?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jdeknoblo** [comment]
if i run the game with cfw will it not auto update?

**Comment by AnimeLove** [comment]
It will still want to update (just block it with DNS, Router or PiHole)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Judeisawesome** [comment]
@AnimeLove I still can't downgrade

**Comment by AnimeLove** [comment]
@Judeisawesome delete old update before installing new

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by AnimeLove** [comment]
@jdeknoblo google it you should find very much tutorials 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Judeisawesome** [comment]
;-; how do I do dat

**Comment by jdeknoblo** [comment]
nice thanks @AnimeLove

**Comment by jdeknoblo** [comment]
@Judeisawesome what i did was i went into my data storage settings and deleted botw update data then just installed the old update via wii u usb helper hb app

**Comment by jdeknoblo** [comment]
@Judeisawesome but you can use wup installer if you'd like to

**Comment by Judeisawesome** [comment]
@jdeknoblo when I delete the data does it automagicly appear in the
wiiuusbhelper??

**Comment by jdeknoblo** [comment]
you have to install the old update data from usb helper onto your sd card and put it in the install folder, once youve done that just delete the new update data in settings and install the old update data

**Comment by Judeisawesome** [comment]
when I use usb helper there is nothing to install. That does not make sense

**Comment by jdeknoblo** [comment]
do you mean on your computer? @Judeisawesome press add update on the wii usb helper app on your computer and put it on your sd cards install folder

**Comment by jdeknoblo** [comment]
if you mean on the app, the files have to be downloaded

**Comment by Judeisawesome** [comment]
@jdeknoblo what site do I need to go to to download the older version

**Comment by jdeknoblo** [comment]
https://www.wiiuusbhelper.com/ download this if you dont already have it, from there you can dowload the older update data, you can also look up a video tutorial if you have to

**Comment by Judeisawesome** [comment]
I need to set up the app

**Comment by Judeisawesome** [comment]
but idk what website to use for the wii u title keys installer part

**Comment by jdeknoblo** [comment]
just look up wii u title keys

**Comment by Judeisawesome** [comment]
@jdeknoblo is this the original 1.5.0 BOTW

00050010

**Comment by jdeknoblo** [comment]
@Judeisawesome uh im not sure you dont have to download the game, just the update data

**Comment by jdeknoblo** [comment]
@Judeisawesome @AnimeLove and also, where is the versions.bin file located because i cant run the game even with my dns blocked because it still wants to update

**Comment by Judeisawesome** [comment]
@jdeknoblo idkhow to get the update data also idk where the game folder is

**Comment by jdeknoblo** [comment]
maybe you have to download the game on your pc to get the update data im not sure
if you have to just watch a tutorial on youtube on how to use wii usb helper

**Comment by jdeknoblo** [comment]
@Judeisawesome @AnimeLove i just need to know how to replace my versions.bin file with the versions.bin file that anime love put in the thread earlier

**Comment by jdeknoblo** [comment]
never mind i figured it out, ty

**Comment by Judeisawesome** [comment]
@jdeknoblo can you make a video on how to downgrade your game??

**Comment by Judeisawesome** [comment]
@everyone can someone make a video on how to downgrad botw?

**Comment by jdeknoblo** [comment]
@Judeisawesome i cant rn but maybe later this week

**Comment by AnimeLove** [comment]
Wait I’ll do

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by AnimeLove** [comment]
Just done making the Video 👌 but make sure to block updates... will send link when it’s uploaded 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by AnimeLove** [comment]
https://youtu.be/ENFHAYVdzzs

Should be Aviable in 30 mins

**Comment by ThisLegitYT** [comment]
You have to wait a few minutes after loading the game and then click the load items button. If that doesn't work you may need to get the DLC which fixed it for me.

**Comment by Judeisawesome** [comment]
boi I used Wii U usb helper to get the game. It is a wrong version. How do I uninstall that new update with the old one.

**Comment by Judeisawesome** [comment]
also, the version.bin still shoes nothing

**Comment by ThisLegitYT** [comment]
i also got the game on wii u usb helper and got the latest version and latest dlc and the trainer worked.

**Comment by Judeisawesome** [comment]
okaythanks! :)
