### ISSUE TITLE
items wont load :/

### ISSUE THREAD

**Issue by jdeknoblo** [joffnerd/botw-trainer#198]
I've tried a lot to fix this problem, I'm on botw version 1.4.1 and my Wii u is 5.5.2 when I load TCP gecko my Wii u's IP shows as 10.0.0- idk if i should give the whole IP. maybe that is the issue but I can connect to my Wii u apparently with the trainer but my items won't load. I've seen a lot of threads like this but I haven't gotten very much help from those. ty in advance

**Comment by jdeknoblo** [comment]
turns out that it isnt the ip, because i could use cheats

**Comment by slicknickthequick** [comment]
My versions are the same as yours. The items won't load for me either.

**Comment by jdeknoblo** [comment]
thats interesting, people were saying that it worked with 5.5.2

**Comment by ThisLegitYT** [comment]
You have to wait a few minutes after loading the game and then click the load items button. If that doesn't work you may need to get the DLC which fixed it for me.
