### ISSUE TITLE
Seems so close! but still, an error... help please!

### ISSUE THREAD

**Issue by Silvace107** [joffnerd/botw-trainer#207]
Errors
Could not load file or assembly 'YamlDotNet, Version=4.2.3.0, Culture=neutral, PublicKeyToken=ec19458f3c15af5e' or one of its dependencies. The system cannot find the file specified.   at BotwTrainer.Offsets.LoadOffsets()
   at BotwTrainer.MainWindow.LoadOffsets()
   at BotwTrainer.MainWindow.MainWindowLoaded(Object sender, RoutedEventArgs e)

After looking though many guides, I have no clue what to do next.

**Comment by piratesephiroth** [comment]
I guess you need YamlDotNet.dll
https://ci.appveyor.com/project/aaubry/yamldotnet/build/artifacts

**Comment by Silvace107** [comment]
Thank you for the URL! I've managed to get botw T. to run!
