### ISSUE TITLE
Exception of type 'BotwTrainer.ETCPGeckoException' was thrown.

### ISSUE THREAD

**Issue by Boldboro** [joffnerd/botw-trainer#25]
Modify a weapon. That error pops up.
Modify a bow. That error pops up.
Change the item value of arrows. That error pops up.
Modify a shield. That error pops up.
Change the item value. That error pops up.

I'm using TCPGecko from the Gecko U update with the right Code bin.
US copy, Version 33 Update, I even just installed the DLC to see if that would've been the problem but the same error pops up.
Only happens with this trainer, but this also to be fair the only trainer I can use to change the item value of things that aren't arrows, but I can't even do that.

I would also like to ask if there is a way I can get the exe for 1.7 back? It seems everytime you update you delete the older exe. I didn't have much problems editing my item values in 1.7, but ever since after 1.7 the trainer will never edit anything for me ever again and only crashes. Now it don't crash no more, it just say an error pops up and the error is what's listed above.

**Comment by joffnerd** [comment]
I reverted  tcpgecko files but other than that I have no idea im afraid. That file is our of my knowledge  zone. You can download  1.7 source and compile if you need. I may be able to do it later.

**Comment by Boldboro** [comment]
That was the only error it gave in the error tab whenever I try to do anything.
I also don't know how to compile.

**Comment by joffnerd** [comment]
New version which should help identify where exactly this happens

**Comment by joffnerd** [comment]
Can you test this please:

https://joffnerd.s3.amazonaws.com/app.publish.test.zip

**Comment by Boldboro** [comment]
Will test when I get home in a moment.

**Comment by Boldboro** [comment]
I just tried to edit something again and this came up:

http://pastebin.com/MFfpRrFS

**Comment by Boldboro** [comment]
When I try to edit material values and not modify what an item is, this comes up:

http://pastebin.com/MDYTDW2w

Can I like completely disable those damn codes as it seems to be the problem. I use breath.exe for codes. I just want to edit and modify my weapons and values. I don't care for the codes.

**Comment by joffnerd** [comment]
See similar issue here

https://github.com/joffnerd/botw-trainer/issues/17#issuecomment-286552203

**Comment by Boldboro** [comment]
I'm not sure how to disable a network card and what I'm supposed to enable. I think I only have one network card.

**Comment by joffnerd** [comment]
Yeah I have no idea whats its not working for you, i'm sorry. Too many variables.

Try 2.6, if that doesn't work then there isn't anything i can do im afraid. I'm a beginner  myself

**Comment by Boldboro** [comment]
What I mean is how do I turn off a network card and pick I guess some other option to use. The comment wasn't clear on what they really did.

**Comment by joffnerd** [comment]
They had 2 network cards, i am just highlighting that there are too many facotrs to understand  why you can't get it to work, it could be anything.

**Comment by Boldboro** [comment]
http://pastebin.com/CNadyWYE
Please tell me how to remove the code tab please. The problem is that code tab.
The codes work on breath.exe and I use breath.exe for codes.

I don't want codes. I want to edit my items and item values. This is really not fair to have the codes tab linked with the other tabs when I thought you said  that one tab acts alone and not part of the other tabs.

So why is the codes tab messing with me in other tabs when I don't even care for them or even have them checked off?
I just want to edit my items. Nothing more. I just want to edit my items.

**Comment by joffnerd** [comment]
You can't. My trainer works and connects differently to the other one, I cant remove it. Sorry

If the codes tab doesn't work then the whole thing wont work,

**Comment by Boldboro** [comment]
So how do I get this to work as I'm the only one it doesn't work for now.

I'm literally the only one that can't use this program.

**Comment by totesadorbs** [comment]
The readme has been updated with new information regarding the dotnet framework version required.

If you haven't already, download and install the latest dotnet framework (link in the readme here on git).

If that doesn't fix the issue, then you can try disabling your network card in Windows. You can do this through either Device Manager or Network and Sharing. I noticed you haven't listed which version of Windows you're using, or what your network setup between your Wii U and computer is (i.e. Does your Computer use ethernet to talk to a router? Is your Wii U connected to your home network via WiFi? etc.). So without that info I can't really give any step-by-step instructions or troubleshoot much further.

I'm assuming the issue is not with your Wii U, or your ability to run TCPGecko and the CodeHandler because you state you were able to use 1.7 with few or no problems. So the issue is likely outdated software or some other conflict with your computer and the trainer.

Hope this helps!
