### ISSUE TITLE
Mon Code doesn't seem to do anything!

### ISSUE THREAD

**Issue by duy64** [joffnerd/botw-trainer#27]
I have tried many things to get this Mon code to work, but it doesn't seem to do anything.
This is the USA version of the game.

**Comment by duy64** [comment]
Using v2.3.2 of the trainer

**Comment by joffnerd** [comment]
I am PAL and haven't go that far yet so I am not able to test it.

**Comment by duy64** [comment]
I think I have not got that far in the game to get this so call Mon for the code to work
