### ISSUE TITLE
Hmm.

### ISSUE THREAD

**Issue by Arch9SK7** [joffnerd/botw-trainer#28]
Not really an issue but more a suggestion for your releases.

Try using ILMerge to add the json to the program so it's back to just one .exe https://ilmergegui.codeplex.com/

I've already been doing it with each update you drop out but it would be nice with your doing it before hand :)

PS. Keep up the great work.
PPS. Here is a list as you are missing some item names in the code such as Bow of light and materials.

`**Swords/1Hand Weapons: ( Weapon_Sword_XXX )**
001 = Traveler's Sword
002 = Soldier's Broadsword
003 = Knight's Broadsword
004 = Boko Club
005 = Spiked Boko Club
006 = Dragonbone Boko Club
007 = Lizal Boomerang
008 = Lizal Forked Boomerang
009 = Lizal Tri-Boomerang
013 = Guardian Sword
014 = Guardian Sword+
015 = Guardian Sword++
016 = Lynel Sword
017 = Mighty Lynel Sword
018 = Savage Lynel Sword
019 = Bokoblin Arm
020 = Lizalfos Arm
021 = Rusty Broadsword
022 = Soup Ladle
023 = Ancient Sword
024 = Royal Broadsword
025 = Forest Dweller's Sword
027 = Zora Sword
029 = Gerudo Scimitar
030 = Moonlight Scimitar
031 = Feathered Edge
033 = Flameblade
034 = Frostblade
035 = Thunderblade
040 = Spring-Loaded Hammer
041 = Eightfold Blade
043 = Torch
044 = Tree Branch
047 = Royal Guard's Sword
048 = Meteor Rod
049 = Blizzard Rod
050 = Thunderstorm Rod
051 = Boomerang
052 = Scimitar of the Seven
053 = Vicious Sickle
056 = ??? Master Sword (unequippable)
057 = Goddess Sword (Skyward Sword Amiibo)
058 = Sword (8-bit Link Amiibo)
059 = Sea-Breeze Boomerang (The Wind Waker)
060 = Fire Rod
061 = Ice Rod
062 = Lightning Rod
070 = Master Sword
071 = Master Sword (not near malice, no charge)
072 = Master Sword (near malice, no charge)
073 = Demon Carver

**Greatswords/2Hand Weapons ( Weapon_Lsword_XXX )**

001 = Traveler's Claymore
002 = Soldier's Claymore
003 = Knight's Claymore
004 = Boko Bat
005 = Spiked Boko Bat
006 = Dragonbone Boko Bat
010 = Moblin Club
011 = Spiked Moblin Club
012 = Dragonbone Moblin Club
013 = Ancient Battle Axe
014 = Ancient Battle Axe+
015 = Ancient Battle Axe++
016 = Lynel Crusher
017 = Mighty Lynel Crusher
018 = Savage Lynel Crusher
019 = Moblin Arm
020= Rusty Claymore
023 = Ancient Bladesaw
024 = Royal Claymore
027 = Silver Longsword
029 = Golden Claymore
030 = Double Axe
031 = Iron Sledgehammer
032 = Woodcutter's Axe
033 = Great Flameblade
034 = Great Frostblade
035 = Great Thunderblade
036 = Cobble Crusher
037 = Stone Smasher
038 = Boat Oar
041 = Eightfold Longblade
045 = Farming Hoe
047 = Royal Guard's Claymore
051 = Giant Boomerang
054 = Boulder Breaker
055 = Edge of Duality
056 = Korok Leaf
057 = Sword of the Six Sages (Twilight Princess)
059 = Biggoron's Sword (Ocarina of Time)
060 = Fierce Deity Sword (Majora's Mask)
074 = Windcleaver

**Spears (Weapon_Spear_XXX)`**

001 = Traveler's Spear
002 = Soldier's Spear
003 = Knight's Halberd
004 = Boko Spear
005 = Spiked Boko Spear
006 = Dragonbone Boko Spear
007 = Lizal Spear
008 = Enhanced Lizal Spear
009 = Forked Lizal Spear
010 = Moblin Spear
011 = Spiked Moblin Spear
012 = Dragonbone Moblin Spear
013 = Guardian Spear
014 = Guardian Spear+
015 = Guardian Spear++
016 = Lynel Spear
017 = Mighty Lynel Spear
018 = Savage Lynel Spear
021 = Rusty Halberd
022 = Farmer's Pichfork
023 = Ancient Spear
024 = Royal Halberd
025 = Forest Dweller's Spear
027 = Zora Spear
028 = Silverscale Spear
029 = Gerudo Spear
030 = Throwing Spear
031 = Drillshaft
032 = Feathered Spear
033 = Flamespear
034 = Frostspear
035 = Thunderspear
036 = Wooden Mop
037 = Serpentine Spear
038 = Fishing Harpoon
047 = Royal Guard's Spear
049 = Ceremonial Trident
050 = Lightscale Trident

**BOWS**

001 = Traveler's Bow
002 = Soldier's Bow
003 = Spiked Boko Bow
004 = Boko Bow
006 = Lizal Bow
009 = Lynel Bow
011 = Strengthened Lizal Bow
013 = Forest Dweller's Bow
014 = Silver Bow
015 = Golden Bow
016 = Swallow Bow
017 = Falcon Bow
023 = Ancient Bow
026 = Mighty Lynel Bow
027 = Dragon Bone Boko Bow
028 = Great Eagle Bow
029 = Phrenic Bow
030 = Steel Lizal Bow
032 = Savage Lynel Bow
033 = Royal Guard's Bow
035 = Knight's Bow
036 = Royal Bow
038 = Wooden Bow
040 = Duplex Bow
071 = Bow of Light
072 = Twilight Bow (Twilight Princess, shoots Light Arrows!)

**Shields**

001 = Wooden Shield
002 = Soldier's Shield
003 = Knight's Shield
004 = Boko Shield
005 = Spiked Boko Shield
006 = Dragonbone Boko Shield
007 = Lizal Shield
008 = Reinforced Lizal Shield
009 = Steel Lizal Shield
013 = Guardian Shield
014 = Guardian Shield+
015 = Guardian Shield++
016 = Lynel Shield
017 = Mighty Lynel Shield
018 = Savage Lynel Shield
021 = Rusty Shield
022 = Royal Shield
023 = Forest Dweller's Shield
025 = Silver Shield
026 = Gerudo Shield
030 = Hylian Shield
031 = Hunter's Shield
032 = Fisherman's Shield
033 = Royal Guard's Shield
034 = Emblazoned Shield
035 = Traveler's Shield
036 = Radiant Shield
037 = Daybreaker
038 = Ancient Shield
040 = Pot Lid
041 = Shield of the Mind's Eye
042 = Kite Shield
057 = Hero Shield (Wind Waker)

**Armour (in the Armour section, you will find that most of the gear in there only shows the _Head part.
That's because most of the armour is shared in sets.
For example, for the Cap of Time, you use the exact same item ID from Armor_200_Head for both the Trousers and the Tunic by changing the sufix _Head for _Upper (Tunic) and _Lower (Trousers).)**

Armor_001_Head --> Hylian Hood
Armor_002_Head --> Hylian Hood *
Armor_003_Head --> Hylian Hood **
Armor_004_Head --> Hylian Hood ***
Armor_005_Head --> Cap of the Wild
Armor_006_Head --> Zora Helm
Armor_007_Head --> Zora Helm *
Armor_008_Head --> Desert Voe Headband
Armor_009_Head --> Snowquill Headdress

Armor_011_Head --> Flamebreaker Helm
Armor_012_Head --> Stealth Mask

Armor_014_Head --> Climber's Bandanna
Armor_015_Head --> Hylian Hood ****

Armor_017_Head --> Radiant Mask

Armor_020_Head --> Soldier's Helm
Armor_021_Head --> Ancestral Helm
Armor_022_Head --> Bokoblin Mask

Armor_024_Head --> Diamond Circlet
Armor_025_Head --> Ruby Circlet
Armor_026_Head --> Sapphire Circlet
Armor_027_Head --> Topaz Earrings
Armor_028_Head --> Opal Earrings
Armor_029_Head --> Amber Earrings

Armor_035_Head --> Cap of the Wild *
Armor_036_Head --> Snowquill Headdress *
Armor_037_Head --> Flamebreaker Helm *

Armor_039_Head --> Cap of the Wild **
Armor_040_Head --> Desert Voe Headband *

Armor_042_Head --> Stealth Mask *
Armor_043_Upper -> Old Shirt
Armor_043_Lower -> Well-Worn Trousers

Armor_045_Head --> Moblin Mask
Armor_046_Head --> Rubber Helm

Armor_048_Head --> Barbarian Helm

Armor_053_Head --> Gerudo Veil (blue)

Armor_055_Head --> Lizalfos Mask
Armor_056_Head --> Lynel Mask

Armor_060_Head --> Cap of the Wild ***
Armor_061_Head --> Cap of the Wild ****
Armor_062_Head --> Zora Helm **
Armor_063_Head --> Zora Helm ***
Armor_064_Head --> Zora Helm ****
Armor_065_Head --> Desert Voe Headband **
Armor_066_Head --> Desert Voe Headband ***
Armor_067_Head --> Desert Voe Headband ****

Armor_071_Head --> Snowquill Headdress **
Armor_072_Head --> Snowquill Headdress ***
Armor_073_Head --> Snowquill Headdress ****
Armor_074_Head --> Flamebreaker Helm **
Armor_075_Head --> Flamebreaker Helm ***
Armor_076_Head --> Flamebreaker Helm ****
Armor_077_Head --> Stealth Mask **
Armor_078_Head --> Stealth Mask ***
Armor_079_Head --> Stealth Mask ****

Armor_083_Head --> Climber's Bandanna *
Armor_084_Head --> Climber's Bandanna **
Armor_085_Head --> Climber's Bandanna ***
Armor_086_Head --> Climber's Bandanna ****
Armor_087_Head --> Radiant Mask *
Armor_088_Head --> Radiant Mask **
Armor_089_Head --> Radiant Mask ***
Armor_090_Head --> Radiant Mask ****

Armor_095_Head --> Soldier's Helm *
Armor_096_Head --> Soldier's Helm **
Armor_097_Head --> Soldier's Helm ***
Armor_098_Head --> Soldier's Helm ****
Armor_099_Head --> Ancestral Helm *
Armor_100_Head --> Ancestral Helm **
Armor_101_Head --> Ancestral Helm ***
Armor_102_Head --> Ancestral Helm ****
Armor_103_Head --> Rubber Helm *
Armor_104_Head --> Rubber Helm **
Armor_105_Head --> Rubber Helm ***
Armor_106_Head --> Rubber Helm ****

Armor_111_Head --> Barbarian Helm *
Armor_112_Head --> Barbarian Helm **
Armor_113_Head --> Barbarian Helm ***
Armor_114_Head --> Barbarian Helm ****
Armor_115_Head --> Thunder Helm

Armor_116_Upper --> Champion's Tunic

Armor_117_Head --> Diamond Circlet *
Armor_118_Head --> Diamond Circlet **
Armor_119_Head --> Diamond Circlet ***
Armor_120_Head --> Diamond Circlet ****
Armor_121_Head --> Ruby Circlet *
Armor_122_Head --> Ruby Circlet **
Armor_123_Head --> Ruby Circlet ***
Armor_124_Head --> Ruby Circlet ****
Armor_125_Head --> Sapphire Circlet *
Armor_126_Head --> Sapphire Circlet **
Armor_127_Head --> Sapphire Circlet ***
Armor_128_Head --> Sapphire Circlet ****
Armor_129_Head --> Topaz Earrings *
Armor_130_Head --> Topaz Earrings **
Armor_131_Head --> Topaz Earrings ***
Armor_132_Head --> Topaz Earrings ****
Armor_133_Head --> Opal Earrings *
Armor_134_Head --> Opal Earrings **
Armor_135_Head --> Opal Earrings ***
Armor_136_Head --> Opal Earrings ****
Armor_137_Head --> Amber Earrings *
Armor_138_Head --> Amber Earrings **
Armor_139_Head --> Amber Earrings ***
Armor_140_Head --> Amber Earrings ****

Armor_148_Upper -> Champion's Tunic *
Armor_149_Upper -> Champion's Tunic **
Armor_150_Upper -> Champion's Tunic ***
Armor_151_Upper -> Champion's Tunic ****

Armor_152_Lower = Sand Boots *
Armor_153_Lower = Sand Boots **
Armor_154_Lower = Sand Boots ***
Armor_155_Lower = Sand Boots ****

Armor_156_Lower = Snow Boots *
Armor_157_Lower = Snow Boots **
Armor_158_Lower = Snow Boots ***
Armor_159_Lower = Snow Boots ****

Armor_160_Head --> Dark Hood (nig-nog Link)

Armor_170_Upper -> Nintendo Switch Shirt

Armor_200_Head --> Cap of Time
Armor_201_Head --> Cap of Time *
Armor_202_Head --> Cap of Time **
Armor_203_Head --> Cap of Time ***
Armor_204_Head --> Cap of Time ****
Armor_205_Head --> Cap of Wind
Armor_206_Head --> Cap of Wind *
Armor_207_Head --> Cap of Wind **
Armor_208_Head --> Cap of Wind ***
Armor_209_Head --> Cap of Wind ****
Armor_210_Head --> Cap of Twilight
Armor_211_Head --> Cap of Twilight *
Armor_212_Head --> Cap of Twilight **
Armor_213_Head --> Cap of Twilight ***
Armor_214_Head --> Cap of Twilight ****
Armor_215_Head --> Cap of Skies
Armor_216_Head --> Cap of Skies*
Armor_217_Head --> Cap of Skies**
Armor_218_Head --> Cap of Skies***
Armor_219_Head --> Cap of Skies****
Armor_220_Head --> Sheik's Mask
Armor_221_Head --> Sheik's Mask *
Armor_222_Head --> Sheik's Mask **
Armor_223_Head --> Sheik's Mask ***
Armor_224_Head --> Sheik's Mask ****
Armor_225_Head --> Fierce Deity's Mask
Armor_226_Head --> Fierce Deity's Mask *
Armor_227_Head --> Fierce Deity's Mask **
Armor_228_Head --> Fierce Deity's Mask ***
Armor_229_Head --> Fierce Deity's Mask ****
Armor_230_Head --> Cap of the Hero
Armor_231_Head --> Cap of the Hero *
Armor_232_Head --> Cap of the Hero **
Armor_233_Head --> Cap of the Hero ***
Armor_234_Head --> Cap of the Hero ****

**Materials**

Fruit:

Item_Fruit_A = Apple (0,5)
Item_Fruit_B = Wildberry (0,5)
Item_Fruit_C = Voltfruit (0,5)
Item_Fruit_D = Hearty Durian (3)
Item_Fruit_E = Fleet-Lotus Seeds (0,5)
Item_Fruit_F = Hydromelon (0,5)
Item_Fruit_G = Palm Fruit (1)
Item_Fruit_H = Mighty Bananas (0,5)
Item_Fruit_I = Spicy Pepper (0,5)
Item_Fruit_J = Fortified Pumpkin (0,5)
Item_Fruit_K = Acorn (0,25)
Item_Fruit_L = Chickaloo Tree Nut (0,25)
_________________________________________________________________

Mushrooms:

Item_Mushroom_A = Stamella Mushroom (0,5)
Item_Mushroom_B = Chillshroom (0,5)
Item_Mushroom_C = Sunshroom (0,5)
Item_Mushroom_D = Rushroom (0,5)
Item_MushroomGet_D = Rushroom (0,5)
Item_Mushroom_E = Hylian Mushroom (0,5)
Item_Mushroom_F = Hearty Truffle (2)

Item_Mushroom_H = Zapshroom (0,5)

Item_Mushroom_J = Silent Shroom (0,5)

Item_Mushroom_L = RazorshroomSchwertling (0,5)
Item_Mushroom_M = IronshroomRüstling (0,5)
Item_Mushroom_N = Big Hearty Truffle (3)
Item_Mushroom_O = Endura Shroom (1)
_________________________________________________________________

Plants:

Item_Plant_A = Hyrule Herb (1)
Item_PlantGet_A = Hyrule Herb (1)
Item_Plant_B = Hearty Radish (2,5)
Item_PlantGet_B = Hearty Radish (2,5)
Item_Plant_C = Big Hearty Radish (4)
Item_PlantGet_C = Big Hearty Radish (4)

Item_Plant_E = Cool Safflina
Item_PlantGet_E = Cool Safflina
Item_Plant_F = Warm Safflina
Item_PlantGet_F = Warm Safflina
Item_Plant_G = Mighty Thistle
Item_PlantGet_G = Mighty Thistle
Item_Plant_H = Armoranth
Item_PlantGet_H = Armoranth
Item_Plant_I = Blue Nightshade
Item_PlantGet_I = Blue Nightshade
Item_Plant_J = Silent Princess
Item_PlantGet_J = Silent Princess

Item_Plant_L = Electric Safflina
Item_PlantGet_L = Electric Safflina
Item_Plant_M = Swift Carrot (0,5)
Item_PlantGet_M = Swift Carrot (0,5)

Item_Plant_O = Swift Violet
Item_PlantGet_O = Swift Violet

Item_Plant_Q = Endura Carrot (2)
Item_PlantGet_Q =Endura Carrot (2)
_________________________________________________________________

Meat:

Item_Meat_01 = Raw Meat (1)
Item_Meat_02 = Raw Prime Meat (1,5)

Item_Meat_06 = Raw Bird Drumstick (1)
Item_Meat_07 = Raw Bird Thigh (1,5)

Item_Meat_11 = Raw Gourmet Meat (3)
Item_Meat_12 = Raw Whole Meat (3)
_________________________________________________________________

Fish:

Item_FishGet_A = Hylian Bass (1)
Item_FishGet_B = Hearty Bass (2)
Item_FishGet_C = Chillfin Trout (1)
Item_FishGet_D = Voltfin Trout (1)
Item_FishGet_E = Mighty Carp (1)
Item_FishGet_F = Mighty Porgy (1)
Item_FishGet_G = Armored Porgy (1)
Item_FishGet_H = Armored Carp (1)
Item_FishGet_I = Hearty Salmon (4)
Item_FishGet_J = Sizzlefin Trout (1)
Item_FishGet_K = Hearty Blueshell Snail (3)
Item_FishGet_L = Staminoka Bass (1)
Item_FishGet_M = Sneaky River Snail (1)

Item_FishGet_X = Stealthfin Trout (1)

Item_FishGet_Z = Sanke Carp (1)
_________________________________________________________________

insects:

Animal_Insect_A = Hot-Footed Frog
Animal_Insect_B = Tireless Frog
Animal_Insect_C = Cold Darner

Animal_Insect_E = Sunset Firefly
Animal_Insect_F = Fairy (5)
Animal_Insect_G = Bladed Rhino Beetle
Animal_Insect_H = Restless Cricket
Animal_Insect_I = Electric Darner

Animal_Insect_K = Razorclaw Crab (1)

Animal_Insect_M = Hearty Lizard
Animal_Insect_N = Winterwing Butterfly
Animal_Insect_O = Ironshell Crab (1)
Animal_Insect_P = Rugged Rhino Beetle
Animal_Insect_Q = Summerwing Butterfly
Animal_Insect_R = Thunderwing Butterfly
Animal_Insect_S = Hightail Lizard
Animal_Insect_T = Warm Darner

Animal_Insect_X = Fireproof Lizard

Animal_Insect_Z = Bright-Eyed Crab
Animal_Insect_AA = Energetic Rhino Beetle
Animal_Insect_AB = Smotherwing Butterfly
_________________________________________________________________

Others:

BeeHome = Courser Bee Honey (2)
Obj_FireWoodBundle = Wood
_________________________________________________________________

Enemy Items:

Item_Enemy_00 = Bokoblin Horn
Item_Enemy_01 = Bokoblin Fang
Item_Enemy_02 = Bokoblin Guts
Item_Enemy_03 = Lizalfos Horn
Item_Enemy_04 = Lizalfos Talon
Item_Enemy_05 = Lizalfos Tail
Item_Enemy_06 = Moblin Horn
Item_Enemy_07 = Moblin Fang
Item_Enemy_08 = Moblin Guts

Item_Enemy_12 = Lynel Horn
Item_Enemy_13 = Lynel Hoof
Item_Enemy_14 = Lynel Guts
Item_Enemy_15 = Red Chuchu Jelly
Item_Enemy_16 = Yellow Chuchu Jelly
Item_Enemy_17 = White Chuchu Jelly
Item_Enemy_18 = Keese Wing
Item_Enemy_19 = Keese Eyeball
Item_Enemy_20 = Octorok Tentakcle
Item_Enemy_21 = Octorok Eyeball

Item_Enemy_24 = Molduga Fin
Item_Enemy_25 = Molduga Guts
Item_Enemy_26 = Ancient Gear
Item_Enemy_27 = Ancient Screw
Item_Enemy_28 = Ancient Spring
Item_Enemy_29 = Ancient Shaft
Item_Enemy_30 = Ancient Core
Item_Enemy_31 = Giant Ancient Core
Item_Enemy_32 = Hinox Toenail
Item_Enemy_33 = Hinox Tooth
Item_Enemy_34 = Hinox Guts

Item_Enemy_38 = Dinraal's Scale
Item_Enemy_39 = Dinraal's Claw
Item_Enemy_40 = Chuchu Jelly
Item_Enemy_41 = Red Lizalfos Tail
Item_Enemy_42 = Icy Lizalfos Tail
Item_Enemy_43 = Yellow Lizalfos Tail
Item_Enemy_44 = Fire Keese Wing
Item_Enemy_45 = Electric Keese Wing
Item_Enemy_46 = Ice Keese Wing
Item_Enemy_47 = Shard of Dinraal's Fang
Item_Enemy_48 = Shard of Dinraal's Horn
Item_Enemy_49 = Naydra's Scale
Item_Enemy_50 = Naydra's Claw
Item_Enemy_51 = Shard of Naydra's Fang
Item_Enemy_52 = Shard of Naydra's Horn
Item_Enemy_53 = Farosh's Scale
Item_Enemy_54 = Farosh's Claw
Item_Enemy_55 = Shard of Farosh's Fang
Item_Enemy_56 = Shard of Farosh's Horn
Item_Enemy_57 = Oct Balloon
_________________________________________________________________

Materials:

Item_Material_01 = Cane Sugar
Item_Material_02 = Goron Spice
Item_Material_03 = Hylian Rice (1)
Item_Material_04 = Bird Egg (1)
Item_Material_05 = Fresh Milk (0,5)
Item_Material_06 = Goat Butter
Item_Material_07 = Tabantha-Wheat (1)
Item_Material_08 = Monster Extract
_________________________________________________________________

Ores:

Item_Ore_A = Diamond
Item_Ore_B = Ruby
Item_Ore_C = Sapphire
Item_Ore_D = Topaz
Item_Ore_E = Opal
Item_Ore_F = Amber
Item_Ore_G = Luminous Stone
Item_Ore_H = Rock Salt
Item_Ore_I = Flint
Item_Ore_J = Star Fragment

**Key Items**

Obj_DungeonClearSeal = Spirit Orbs
Obj_KorokNuts = Korok Seeds
PlayerStole2 = Paraglider
Obj_ProofBook = Secret Documents
Obj_DRStone_Get = Shiekah Slate
Obj_HeroSoul_Zora = Mipha's Grace
Obj_HeroSoul_Gerudo = Urbosa's Fury
Obj_HeroSoul_Goron = Daruk's Protection
Obj_HeroSoul_Rito = Revali's Gale
Obj_Maracas = Hestu's Maracas

GameRomHorseReins_00 = Stable Bridle
GameRomHorseSaddle_00 = Stable Saddle
GameRomHorseReins_01 = Traveler's Bridle
GameRomHorseSaddle_01 = Traveler's Saddle
GameRomHorseReins_02 = Royal Bridle
GameRomHorseSaddle_02 = Royal Saddle
GameRomHorseReins_03 = Knight's Bridle
GameRomHorseSaddle_03 = Knight's Saddle
GameRomHorseReins_04 = Monstrous Bridle
GameRomHorseSaddle_04 = Monstrous Saddle
GameRomHorseReins_05 = Extravagant Bridle
GameRomHorseSaddle_05 = Extravagant Saddle

**Comment by joffnerd** [comment]
Wow great list, I won't have time to turn it into json  though :( if you can be bothered please pull down the source, modify items.json and do a pull request.  I will check out that merge code. Thanks very much!

**Comment by Arch9SK7** [comment]
Doing that now.

**Comment by joffnerd** [comment]
What settings do you use for ILMErge? Just tried it but the resulting exe doesn't run.

**Comment by Arch9SK7** [comment]
Just as such. Drag both files into it http://prntscr.com/ej4b9f

**Comment by Arch9SK7** [comment]
hmm ignore the merge piece then. i am now getting errors not sure why.
