### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by xNeptune** [joffnerd/botw-trainer#33]
From experience with the BOTW game and the trainer I've found that it's only possible to *edit* armor items, rather then *adding* new ones. I was wondering if it would be possible when you have time to allow the trainer to load extra slots from memory in order to be edited or if that would cause errors due to injecting items that were not previously there. I'm sure there is numerous methods to approach this and although my C# knowledge isn't extensive enough to code this myself I can still try to help and provide to the best of my ability.

**Comment by joffnerd** [comment]
Yeah at the  moment you can only edit what you have, i have tried adding new things in memory but they don't appear like when you pick something new up.

I think DarkFlare  on GBA has started to figure out how to do this though
