### ISSUE TITLE
2.5.5 doesn't connect, screws up network connection

### ISSUE THREAD

**Issue by Ailuros** [joffnerd/botw-trainer#37]
Running Windows 7, and having made no changes to my computer or Wii U other than updating the trainer from 2.5.1 (which I was using successfully yesterday) to 2.5.5, I can no longer use the trainer at all. It doesn't connect, but instead gives the "Reached max number of attempts" error in the error tab. Then, when I go to look up the solution, or really do anything involving my computer's network connection, it's completely unresponsive at random intervals. Only rebooting seems to restore my network connection. I have now rebooted 3 times to try to pin down the problem, and after going back to version 2.5.1 of the trainer fixes things. I'm using the latest files from Bully's Gecko U updater and have exclusions set in my antivirus to rule those out.

**Comment by Ailuros** [comment]
Now when I try load data with 2.5.1 I get this error:
Exception of type 'BotwTrainer.ETCPGeckoException' was thrown.   at BotwTrainer.TCPGecko.Dump(UInt32 startdump, UInt32 enddump, Stream[] saveStream)
   at BotwTrainer.TCPGecko.peek(UInt32 address)
   at BotwTrainer.MainWindow.LoadDataAsync()

**Comment by joffnerd** [comment]
I reverted the connection code, i dont think the c# connection stuff is as stable as jgecko u

https://github.com/joffnerd/botw-trainer/releases/tag/v2.5.6
