### ISSUE TITLE
Trainer crash 

### ISSUE THREAD

**Issue by Gdye1991** [joffnerd/botw-trainer#40]
I put in my wii u's ip and connect to it but when I try to load my data in i get an error saying that botw trainer has stopped I downloaded 2.5.5 and 2.5.6 any input would help

**Comment by joffnerd** [comment]
No error message at all? When you click load data after connecting?

**Comment by Gdye1991** [comment]
No it just stops responding and exits the program and asks if I would like to report the problem

**Comment by Gdye1991** [comment]
And yes it connects to my wii u's ip then when I hit load data it just crashes

**Comment by joffnerd** [comment]
[app.publish.zip](https://github.com/joffnerd/botw-trainer/files/845609/app.publish.zip)

That should catch the error, can you post what it says please? Error Tab

**Comment by Gdye1991** [comment]
Yes I'll have to do it when I get off work tho has anyone else seen a problem like this?

**Comment by joffnerd** [comment]
Loads, there are too may variables to know what it might be. Could be your region, could be your network, could be the  way you load tcp gecko

**Comment by Gdye1991** [comment]
Alright well when I get home I'll see what I can do

**Comment by Gdye1991** [comment]
How does this app publish work exactly will it give me a list of errors or what?

**Comment by joffnerd** [comment]
that just a new version of the trainer with an error check on the load button

**Comment by Gdye1991** [comment]
i downloaded the version you linked to and its just freezing and closing the program as well it gives no error logs or anything i have to run sigpatcher in order to run the game because of the update but would that cause it to crash?

**Comment by Gdye1991** [comment]
windows gave these files as the issue
  C:\Users\Ashley\AppData\Local\Temp\WER4605.tmp.WERInternalMetadata.xml
  C:\Users\Ashley\AppData\Local\Temp\WER694E.tmp.appcompat.txt
  C:\Users\Ashley\AppData\Local\Temp\WER6C8A.tmp.mdmp

**Comment by Gdye1991** [comment]
I fixed it my .net framework was outdated and throwing connection errors
