### ISSUE TITLE
"Can't read item at address: 0x43CA2B08   en BotwTrainer.MainWindow.LoadDataAsync()"

### ISSUE THREAD

**Issue by BowserFan** [joffnerd/botw-trainer#42]
Everytime i try to use this , when i click "Load" it brings up this error on the error tab.
Any idea why? My game is USA region and i also got 1.1 version

**Comment by joffnerd** [comment]
Disable your anti virus?

**Comment by BowserFan** [comment]
My anti virus doesnt brings anything :o

**Comment by BowserFan** [comment]
Also , more info: 
OS: Windows 7 SP1
Wii U Firmware: 5.5.1 U
Game Region: US

**Comment by joffnerd** [comment]
Make sure your .net is latest version. Check readme

**Comment by totesadorbs** [comment]
Check your dotnet version

**Comment by BowserFan** [comment]
I downloaded the .net latest version , however , now im getting this:

El valor no puede ser nulo. / Value cannot be null.
Nombre del parámetro / Name of Parameter: text   en System.Windows.Documents.InlineCollection.AddText(String text, Boolean returnIndex)
   en BotwTrainer.MainWindow.LogError(Exception ex, String more)
   en BotwTrainer.MainWindow.ConnectClick(Object sender, RoutedEventArgs e)

**Comment by djvj1** [comment]
Just got this trainer and getting this same error:
Can't read item at address: 0x43CA2B08   at BotwTrainer.MainWindow.LoadData()

OS: WIn10
Wii U: 5.5.1U
Game Region: US
Notes: No anti-virus. Also when I try to install the suggested .net, it says I already have it or a later version installed.

Not sure what to try next?

**Comment by joffnerd** [comment]
Yes you need Bullys TCPGecko as it uses specific server commands that my trainer talks to like JGecko U
