### ISSUE TITLE
Amiibo Suggestion

### ISSUE THREAD

**Issue by JellyBelly12346** [joffnerd/botw-trainer#45]
You should add a tweak that will trick the game into thinking you've added an amiibo.
Now, I know you already said you doubt you can do it but I think you can, and there are other TCP hacks that have done this. Splat AIO 2 lets you do it. I tried getting in contact with the creator of it to see how it works, I've figured out a way to do it with smash bros on Gecko dNet. I just can't figure out how to insert the file in such a way that it would trick Zelda: BoTW into thinking it as I do not have any Zelda amiibo's. I think you should at least toy around with it, it would be amazing to get Epona, or maybe you can find a way to replace your current horse's texture with Epona?

**Comment by JellyBelly12346** [comment]
Like maybe get your horse's normal texture and just replace it rather than getting Epona itself. Yeah, there would be a bunch of Epona's everywhere but at least you would have Epona?

**Comment by joffnerd** [comment]
OK. Please stop making this an issue though
