### ISSUE TITLE
will not connect to WiiU anymore

### ISSUE THREAD

**Issue by 0100100001001001** [joffnerd/botw-trainer#47]
Using version 2.7

-----------------------------------------------------------------
Error data will appear here
Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at BotwTrainer.TcpConn.Read(Byte[] buffer, UInt32 nobytes, UInt32& bytesRead)
   at BotwTrainer.Gecko.GetServerStatus()
   at BotwTrainer.MainWindow.ConnectClick(Object sender, RoutedEventArgs e)

------------------------------------------------------------------
JGeckoU can connect, and I have no issues using earlier versions of the trainer.  Used BullyWiiPlazas Gecko updater as stated in your trainer.

JGeckoU will not connect after the trainer has failed, and it puts my PCs network setting into airplane mode??? If I exit the game on the WiiU everything goes back to normal, and JGeckoU will connect again.  I hope this helps in someway.

Thank you for your time and effort in making this trainer.

**Comment by 0100100001001001** [comment]
UPDATE

Disabling Avast antivirus fixed the issue

**Comment by joffnerd** [comment]
Thanks. Good to know in case it happens to others
