### ISSUE TITLE
Method not found

### ISSUE THREAD

**Issue by navidad626** [joffnerd/botw-trainer#48]
Everytime I click connect it gives this error (view image) my IP is correct I installed TCPGecko with CosmoCourtney Codehandler correctly as well, JGecko work but this doesn't. Its not my antivirus either, please help and thank you for making this Trainer for us.
![capture](https://cloud.githubusercontent.com/assets/26472674/24025236/87656486-0a76-11e7-8fe6-0431b10602de.PNG)

**Comment by joffnerd** [comment]
What .Net version do you have installed?

**Comment by totesadorbs** [comment]
Link to latest here:
https://www.microsoft.com/en-us/download/details.aspx?id=53344
(offline installer)
Error solved for me with latest framework update linked above.
Hope this helps!

**Comment by navidad626** [comment]
I updated my .Net and it solved my issue, Thank you guys!
