### ISSUE TITLE
Regarding Method Not Found Errors

### ISSUE THREAD

**Issue by totesadorbs** [joffnerd/botw-trainer#49]
Hi, just a quick piece of information and a suggestion regarding the new errors of "Method Not Found" when clicking connect and/or performing similar actions that have been noticed (by myself included) with version 2.6 and forward.

I noticed after a bit of research on the issue, the error relates to the program calling an instruction added to the dotnet framework in a later version than the user's system has.

I then also realized that you've never told anyone what version of the dotnet framework you are using, or which version they should have.

I believe quite a few errors can be solved and/or avoided entirely by adding the following to the readme and any relevant posts on certain forums.

"IN ORDER TO USE THIS PROGRAM YOU REQUIRE THE LATEST VERSION OF DOTNET FRAMEWORK (4.6.2). IF YOU DO NOT HAVE THIS, OR ARE NOT SURE IF YOU HAVE THIS, FOLLOW THIS LINK (https://www.microsoft.com/en-us/download/details.aspx?id=53344). DOWNLOAD AND INSTALL"

In addition, concerning all future troubleshooting/debugging/etc. I would absolutely begin the process of helping a user/tester etc. by asking them immediately, up front, what version of dotnet framework they have installed, and if they have tried the installer at the above link to make sure it is correctly installed (additionally it doesn't hurt to restart the computer after installing the framework, and always run this program as administrator just in case the account they're using has an extremely odd set of permissions or other such not-program-bug-related problem.

Hope this helps, I really think a lot of headaches and unncessary diagnostic/coding work can be avoided this way. Thank you so much for the trainer, I very very much appreciate the time and effort you've put into it!!!

**Comment by 0100100001001001** [comment]
Good point.  Maybe make the red text you have in the upper right corner of the trainer refresh and say this too.  You know, make it kind of go through all the known issues and solutions,  or in the ( Help ) tab if it would show the version of required programs and program libraries you have, and the versions you need.  I'm not a programmer though, so I have no idea what would be involved in that.

**Comment by joffnerd** [comment]
Thanks for this, i merged your readme
