### ISSUE TITLE
Traienr Icon

### ISSUE THREAD

**Issue by dwatts23** [joffnerd/botw-trainer#52]
After downloading the latest trainer I click on the icon and nothing happens, and it doesn't open. Any suggestions?

**Comment by joffnerd** [comment]
Did a previous version work? Did you extra the newtonsoft dll as well?

**Comment by trunkzcr** [comment]
My solution is to unistall .net and install back

**Comment by joffnerd** [comment]
Great. You need the latest version which is linked to in the readme

**Comment by dwatts23** [comment]
Yes, I was using an older version and then downloaded the newest version and the newest version wouldn't even attempt to open. I'll try again, tho. BTW, the trainer is awesome and am glad you are keeping up on the updates for us. Much appreciated. 

    On Saturday, March 18, 2017 3:19 AM, Joff <notifications@github.com> wrote:
 

 Closed #52.—

**Comment by dwatts23** [comment]
So, I figured out the problem could be that I didn't extract Newtonsoft. How do I extract it through WinZip, and where do I extract it to? Your help is much appreciated. 

    On Saturday, March 18, 2017 3:33 PM, david watts <davidwatts232@yahoo.com> wrote:
 

 Yes, I was using an older version and then downloaded the newest version and the newest version wouldn't even attempt to open. I'll try again, tho. BTW, the trainer is awesome and am glad you are keeping up on the updates for us. Much appreciated. 

    On Saturday, March 18, 2017 3:19 AM, Joff <notifications@github.com> wrote:
 

 Closed #52.—
