### ISSUE TITLE
[Error] Value cannot be null.

### ISSUE THREAD

**Issue by Kitsumi** [joffnerd/botw-trainer#53]
**Version:** 2.7, 3.0, 3.1
**OS:** Windows 10
**Wii U Firmware:** 5.5.1 U
**Game Region:** US
**Additional Notes:** This only seems to happen when the internet signal kinda sucks.
**Error:**
```
Value cannot be null.
Parameter name: text   at System.Windows.Documents.InlineCollection.AddText(String text, Boolean returnIndex)
   at BotwTrainer.MainWindow.LogError(Exception ex, String more)
   at BotwTrainer.MainWindow.ConnectClick(Object sender, RoutedEventArgs e)
```

**Comment by joffnerd** [comment]
Yeah sounds like it can't communicate with the Wii via the TCP connection :(

**Comment by mothbelly** [comment]
I've been getting this error too, but it seems to happen regardless of connection. Switching between networks didn't help. It's a shame because this had been working flawlessly before.

**Comment by Ailuros** [comment]
Yeah. I'm not sure what this is. I'm getting it, too. I wonder if it has anything to do with the resizeability of the window.

**Comment by joffnerd** [comment]
It can't read the coordinates from the wii. Its getting back the value of 0 for the pointer location which isn't a legitimate coordinate.

**Comment by joffnerd** [comment]
Try clicking the follow pointer button in jgecko u and testing both of these lines

[0x439BF780] + 0x140
[0x439BF794] + 0x140

**Comment by totesadorbs** [comment]
Also, for those with the null pointer error. Are you certain that you are loading TCPGecko with the CodeHandler option (pressing X to load, NOT pressing A)? I've caught myself doing this once or twice over time as well, lol. This may not be the cause of the issue at all, but it's at least one more possibility we can cross off if that's not the issue.

Hope this helps!

**Comment by djvj1** [comment]
I'm getting the same error and can use the other trainer just fine, so it's something only happening with this trainer :(

**Comment by joffnerd** [comment]
Please make sure you are using the files referenced in the readme. Specifically .net version and  the tcpgecko files that bully compiled
