### ISSUE TITLE
Unable to read data

### ISSUE THREAD

**Issue by katedering** [joffnerd/botw-trainer#55]
Getting this error every time with version 3.1 - prior versions just state "unable to connect to TCPGecko" or "botw.exception.something-or-other"

Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at BotwTrainer.TcpConn.Read(Byte[] buffer, UInt32 nobytes, UInt32& bytesRead)
   at BotwTrainer.Gecko.GetServerStatus()
   at BotwTrainer.MainWindow.ConnectClick(Object sender, RoutedEventArgs e)

All I'm doing is clicking "Connect" with the WiiU's IP.

EDIT: 2.5.6 works fine.

**Comment by joffnerd** [comment]
check your .net version and turn off anti virus?
