### ISSUE TITLE
I/O error occurred. 

### ISSUE THREAD

**Issue by DJPeters42** [joffnerd/botw-trainer#57]
The trainer was working just fine until I tried editing items in multiple tabs at once without hitting "save" in between. The error below was given and the game froze. Each subsequent attempt yielded the same error:

    Code
    I/O error occurred.   at BotwTrainer.Gecko.ReadBytes(UInt32 address, UInt32 length)
       at BotwTrainer.Gecko.GetString(UInt32 address)
       at BotwTrainer.MainWindow.DebugData()

**Comment by joffnerd** [comment]
Yeah one tab at a time or you try and read from an item that moved

**Comment by xNeptune** [comment]
I'm usually able to edit numerous tabs at a time myself? What tabs were you trying to change without saving?

**Comment by joffnerd** [comment]
Yeah I don't have an issue either, I think because this is over wifi it adds a whole extra layer of complication as everyone's setup is different.
