### ISSUE TITLE
Speed and Moon Jump (Hold B & X) not working

### ISSUE THREAD

**Issue by alromaithi1** [joffnerd/botw-trainer#59]
I really thank you for the trainer (^_^)b

All the codes working, and speed select was ok in 3.2 but the moon jump was not working "Hold X" .

However, now the speed and moon jump is not working in the latest update 3.3 . \(>.<)/

Can you advice on what to do to make it work? I kept holding B and failed and X with the same result, not sure how to do that. ~(;_;)~

**Comment by joffnerd** [comment]
Have you picked the correct controller type?

**Comment by alromaithi1** [comment]
Thank you!! Really Thank you!

I really feel stupid missing that, it worked great (^_^)b

Thanks joffnerd! : D

**Comment by alromaithi1** [comment]
But still , there is one issue noticed in "hold B" speed option, if i am gliding, and i pressed b to speed up it will cancel the glide and fall.

Previously i activate speed and glide all the way in a marveluos speed.

can you make it optional on the next release?

Thanks again (^_^)b

**Comment by joffnerd** [comment]
Yeah i noticed this, I think i might make it a shoulder button in the next release
