### ISSUE TITLE
Trainer won't rescan after reconnect (v1.9)

### ISSUE THREAD

**Issue by Gadorach** [joffnerd/botw-trainer#6]
As it says in the title, the new version won't load the new values again after disconnecting and reconnecting the trainer to the Wii U.

**Comment by joffnerd** [comment]
Closed and re-opened? Are you connected via JGecko U as well?

**Comment by Gadorach** [comment]
Nothing else is connected. I think it's a simple UI bug.

It happens after you connect and load values for the first time. If you click the disconnect button, then click the connect button again, the trainer won't offer you the ability to refresh.

It probably happened when you added the initial load button to the top of the trainer instead of reusing the Refresh button like the older versions. My guess is the disconnect button is disabling the Refresh UI element, then on reconnect the trainer isn't re-enabling the Load Data button, as it's already hidden itself after the initial click.

Probably a quick fix by just having the disconnect button unhide the top Load Data button.

**Comment by joffnerd** [comment]
OK, I will investigate. Thanks!

**Comment by joffnerd** [comment]
This should be fixed now
