### ISSUE TITLE
'PAL' title bar

### ISSUE THREAD

**Issue by mancoast** [joffnerd/botw-trainer#60]
The engine also functions as expected with USA version 1.1.0 BOTW using WIIU fw 5.5.1.

**Comment by mancoast** [comment]
![image](https://cloud.githubusercontent.com/assets/7040493/24128205/cfdf8858-0db0-11e7-9a4e-4ed2bc1ce82f.png)

![image](https://cloud.githubusercontent.com/assets/7040493/24128224/efad9b02-0db0-11e7-956d-4245d276dc46.png)

**Comment by joffnerd** [comment]
Will add this in, thanks
