### ISSUE TITLE
Will not connect

### ISSUE THREAD

**Issue by xxcthomasxx** [joffnerd/botw-trainer#63]
I just downloaded the v3.3 trainer and i cannot get it to connect.  I tried previous versions of the trainer and they connect with no problem.  Here is the error it is giving.

Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at BotwTrainer.TcpConn.Read(Byte[] buffer, UInt32 nobytes, UInt32& bytesRead)
   at BotwTrainer.Gecko.GetServerStatus()
   at BotwTrainer.MainWindow.ConnectClick(Object sender, RoutedEventArgs e)

Edit:  I have tried all versions down till 2.5.6.   That is the last version i can get to connect.  I have tried to update my tcpgecko with the updater by bully.  That doesn't fix the problem.

**Comment by joffnerd** [comment]
It can't get the status of bullys tcp gecko

Is your antivirus or firewall blocking it?

**Comment by joffnerd** [comment]
Also check you have .net 4.6.2

**Comment by xxcthomasxx** [comment]
Its working now.  I downloaded 3.5 and it connected no problem.  i don't know what was causing it.  I havn't changed anything.
