### ISSUE TITLE
Value cannot be null x2

### ISSUE THREAD

**Issue by Nejaime** [joffnerd/botw-trainer#69]
Sorry for bringing an already discussed topic, but im a beginner at gecko and wiiu modding. I used your trainer at v2.6 i guess with no problem, but i decided to start a new save, i downloaded the new version (v3.5) and im having this error, just like the other issue topic it don't seems to be the internet. What should i do?

**Comment by joffnerd** [comment]
Can you give a bit more info please. What causes it to happen?

**Comment by Nejaime** [comment]
whenever i try to connect in the trainer via pc, i cant connect on Jgecko too, i get thi error: java.net.ConnectExeception: Connection timed out

**Comment by joffnerd** [comment]
sounds like you are using the wring ip for you wii. or perhaps its being blocked by firewall / antivirus

**Comment by Nejaime** [comment]
i use the ip i get from the internet app in the wiiu (developer options) cus i WNetWatcher cant find wiiu's ip, and i already tried turning off the antivirus and adding an exception on Windw's firewall

**Comment by joffnerd** [comment]
Are you using the tcpgecko files bully created?

**Comment by Nejaime** [comment]
yes

**Comment by joffnerd** [comment]
I would try and get jgecko working first. Both not working suggests a problem your end. Sorry

**Comment by zeldalinky** [comment]
hi this my very first time to I use the verison 3.5 today then when I got back from home it just it was working just fine no problem at all but it got me the same error wha ipost to do?

**Comment by zeldalinky** [comment]
yes I update to the new vr3.6 nothing good happen
just the same error I rested my wii u n I restart over the it give me the B.S idk what to do cuz it was my very first hack wii u on homebrew n zelda

**Comment by zeldalinky** [comment]
this is the error sorry if miss spelled(Error data will appear here
Value cannot be null.
Parameter name: text   at System.Windows.Documents.InlineCollection.AddText(String text, Boolean returnIndex)
   at BotwTrainer.MainWindow.LogError(Exception ex, String more)
   at BotwTrainer.MainWindow.ConnectClick(Object sender, RoutedEventArgs e)

**Comment by wilhitewarrior** [comment]
I had this same issue. For me it was because I was using the wrong IP. I downloaded Wireless Network Watcher. One of the IPs on that list will be your wii U. One way to determine which is by turning the wii u off and seeing which one it lists as inactive. Or you could simply go down through the list til you find the right one

**Comment by xNeptune** [comment]
I can't express how important it is to have the correct IP address to the wii u, that seems to be the issue due to jgecko not working either. Google how to check ips on your network through the cmd prompt or search how to see connected devices on your router page.

**Comment by joffnerd** [comment]
Closing as over a week old
