### ISSUE TITLE
I'm very new to this, day one new actually. 

### ISSUE THREAD

**Issue by L3nggao** [joffnerd/botw-trainer#71]
Value cannot be null.Parameter name: text   at System.Windows.Documents.InlineCollection.AddText(String text, Boolean returnIndex)   at BotwTrainer.MainWindow.LogError(Exception ex, String more)   at BotwTrainer.MainWindow.ConnectClick(Object sender, RoutedEventArgs e)

**Comment by L3nggao** [comment]
What do I have to do?

**Comment by L3nggao** [comment]
Method not found: 'Void System.net.sockets.tcpClient.Dispose()'. is what I'm getting on startup.

**Comment by Nejaime** [comment]
im getting the same error .-. Value cannot be null, if u find the solution pls let me know.

**Comment by joffnerd** [comment]
You haven't installed. Net 4.6.2

**Comment by L3nggao** [comment]
I'll try it out, thank you sir.

**Comment by L3nggao** [comment]
Value cannot be null.
Parameter name: text   at System.Windows.Documents.InlineCollection.AddText(String text, Boolean returnIndex)
   at BotwTrainer.MainWindow.LogError(Exception ex, String more)
   at BotwTrainer.MainWindow.ConnectClick(Object sender, RoutedEventArgs e)

Still appears, the other popup is now gone. 
Does this mean it's just me being in the US? Or is there another program I missed?

**Comment by L3nggao** [comment]
Got it working, the rupees and etc at least. 
Thanks I appreciated it.
