### ISSUE TITLE
Addition of always run

### ISSUE THREAD

**Issue by alromaithi1** [joffnerd/botw-trainer#73]
Can you add always run option tick box on your next release, as keep holding A + ZL + X and view surroundings is hard. 

Thanks (^_^)v

**Comment by joffnerd** [comment]
I actually removed it as the speed code sort of makes it redundant. I can add it back in though

**Comment by alromaithi1** [comment]
It will be a great way to travel as an option when going long distance. :)

Really thank you joffnerd. (^_^)b

**Comment by joffnerd** [comment]
I will add this back in next release
