### ISSUE TITLE
Horse Whips/Bomb Time

### ISSUE THREAD

**Issue by Link888** [joffnerd/botw-trainer#74]
Hi first of all THANK YOU for sharing your amazing work I love your trainer! It has always worked perfectly I have the US version I think since I live in Canada. The only think that does not work is the Horse Whips and the Bomb Time options.

When I activate Horse Whips and whip the horse the spools get used randomly, and I get dropped by my horse even if on the screen spool 1 and 4 (if the horse has 4 spools and since they are used randomly) are ready to be used. I also noticed I can only whip it 3 times with the code activated rather than the available 4.

When Bomb Time is activated the bomb's timer stops/gets stuck at 50% of the way whether I throw a bomb or not which means I cannot throw any more bombs and the timer circle is on the screen permanently.

Thank you again for your time and hopefully you can take a look at those two codes. I'm hoping US version is not the issue since everything else works but those two might be slightly different addresses :(

Cheers 👍

**Comment by joffnerd** [comment]
Thanks  for the kind words! The codes are those found by users on GBA temp. I will try the horse one but the bomb code is fine here. I will try and investigate

**Comment by Link888** [comment]
Damn you are quick! On v3.6.2 Bomb Time is working perfectly, and with all the options available like speed and moon jump who needs horse whips; however, I do use the horse whip trick anyway holding ZL+ZR+A+Tap X or Tap X,A,X quickly while galloping to get off and on the horse while moving to reset the spools.

Thanks boss! keep up the good work.
