### ISSUE TITLE
I have a request :0

### ISSUE THREAD

**Issue by BotAletz** [joffnerd/botw-trainer#77]
I don't know if it would be possible to include a durability manager or something :).

**Thank You**

**Comment by joffnerd** [comment]
The value is the durability

**Comment by BotAletz** [comment]
Yes but everytime i set the durability like 270F on Hex, it still brakes

**Comment by joffnerd** [comment]
Max value is 6553500 then save in the trainer. Then save and load your game on the wii

**Comment by BotAletz** [comment]
Thanks

**Comment by BotAletz** [comment]
But all my things still break :(

**Comment by joffnerd** [comment]
You aren't doing it right it so.

**Comment by BotAletz** [comment]
Can you show me :)

**Comment by rEd2k** [comment]
lol. Set the durability then save the game and even fast travel and then save again what ever you have to do to get it to stick, THEN load the saved game and your high durability should stick for sure. I have to do this some times, but for the most part you can set the high value then just save the game and then immediately load that save game you just made, the saved durability should be there now. DON'T FORGET to use the refresh button before editing anything! ;)

**Comment by BotAletz** [comment]
Thanks
