### ISSUE TITLE
Every version brings a new error...

### ISSUE THREAD

**Issue by awakenedCrowl** [joffnerd/botw-trainer#78]
This trainer somehow doesn't like me. On version 1.3, I could still connect and try to apply codes which didn't throw any error but didn't work either. On version 3.2 I couldn't even connect (which was because I was using a kinda broken version of TCPGecko) after fixing that, I could connect on 3.2 but it would throw an error when loading the game files.

Now, on 3.62 I can't connect (Avast disabled, run in Administrator Mode) and it throws this error:

```
"Connection closed.   bei BotwTrainer.TcpConn.Read(Byte[] buffer, UInt32 nobytes, UInt32& bytesRead)
   bei BotwTrainer.Gecko.ReadDataBufferSize()
   bei BotwTrainer.Gecko..ctor(TcpConn tcpConn, MainWindow mainWindow)
   bei BotwTrainer.MainWindow.ConnectClick(Object sender, RoutedEventArgs e)"
```

("bei" = "in"/"by" in case someone is confused by that, my PC uses german language)

Thanks in advance

ps. Another weird thing: even though I downloaded the 1.4 homebrew launcher, it somehow only works when choosing 1.3 on loadiine.ovh

Also, breath.exe for example works just fine

**Comment by awakenedCrowl** [comment]
Also, breath.exe used to work perfectly fine, until I reinstalled TPCGecko, now it doesn't work as well.
Breath.exe still "connects" but no code works

**Comment by joffnerd** [comment]
I don't use loadiine. I launch Bully's tcpgecko from homebrew and load game normally.

**Comment by joffnerd** [comment]
What's your .Net version?

**Comment by awakenedCrowl** [comment]
Apparently the newest one, at least it said that when I tried tu update it

**Comment by joffnerd** [comment]
Over 2 weeks old, closing
