### ISSUE TITLE
Item values will not change majority of the time.

### ISSUE THREAD

**Issue by Boldboro** [joffnerd/botw-trainer#8]
I've edited durability. Saved and loaded. That worked fine.
I've edited the values of arrows. Without reloading, that worked fine.
I've edited everything else to 999. Hit save. No changes.
I've edited everything else to 999. Hit save and reloaded. No changes.
I usually have to get the editor to "not responding" at least 6 to 8 times with my game crashing while saving about the same 6 to 8 times to maybe luckily see my values change to 999.

At the moment, I'm above that 8 mark and I don't get why the items seems the near impossible to edit for me.

**Comment by joffnerd** [comment]
Save each tab at a time. Save is linked to the current tab. 

Are you US region?

**Comment by Boldboro** [comment]
I'm only on one tab. The materials.
I'm now up to the 15th try with my Wii U crashing trying to save with BOTW Trainer crashing at times too.
This isn't a new issue either as this been happening since I've tried this trainer.

I'm on US version.

**Comment by joffnerd** [comment]
I am PAL so there must be some Address differences, I'm afraid I cant do much as I don't have the US version to check against. Can you screenshot the codes page please and maybe some of the debug page?

**Comment by Boldboro** [comment]
Codes: http://oi66.tinypic.com/33tr03l.jpg
Debug: http://oi63.tinypic.com/4q315c.jpg

Note: The values that are at 999 were already at 999 before I even tried editing.

**Comment by joffnerd** [comment]
Thanks, I will try and look later but on the debug tab there are no values for the Address column which i can see is wrong. Also on the codes tab the value for health is wrong as its pulling in 0

I guess this data is different for US. Can you use JGecko U to dump from 43000000 - 44000000 for me please?

**Comment by Boldboro** [comment]
I actually never got JGecko U to work for me before. Everytime I tried to use it, it would crash my Wii U. I used TCPGecko before to dump the values for me.

But now there's a problem as it seems that at least tonight that I tried to see if I can find the item values myself... TCPGecko would crash the game as well now after getting around 5% in the dumping.

**Comment by joffnerd** [comment]
https://github.com/BullyWiiPlaza/Gecko-U-Updater

Run that and update the tcpgecko files on your SD card

**Comment by Boldboro** [comment]
I don't have any tcpgecko files on my sd card. I use Loadiine.ovh to load into tcpgecko.

**Comment by joffnerd** [comment]
This is why, that's a very old method and the code handler is out of date

Sorry

**Comment by Boldboro** [comment]
Where can I get an up to date tcpgecko?
The one linked here won't even load up in HBL: https://gbatemp.net/threads/the-legend-of-zelda-breath-of-the-wild-trainer-eshop-eu-beta.463066/

**Comment by Boldboro** [comment]
Dump: https://www.sendspace.com/file/lv7b9p

**Comment by joffnerd** [comment]
I am not sure how it works via Loadiine to be honest. The method of choice is to load TcpGecko via HB app using the files you can get from that jgecko u updater I linked to above. Ta

**Comment by Boldboro** [comment]
Dump posted.

**Comment by Boldboro** [comment]
New Dump as it seems that there was an error in the last one:
https://www.sendspace.com/file/pkg3yz

**Comment by joffnerd** [comment]
Thanks, I will try and  compare it to EUR version tomorrow

**Comment by joffnerd** [comment]
Sorry but I can't support Loadiine method :(
