### ISSUE TITLE
More info

### ISSUE THREAD

**Issue by Rutrow** [joffnerd/botw-trainer#82]
To be more specific to the last message...a couple days ago the trainer
bottom loading bar would fill and a few items would be available for
use. Now on all trainer versions the loading bar indicates 0/0 and when
I press the load items button a pop-up says trainer is unresponsive and shuts
down. Please help as I would love to aquire weapons.

Thanks. Rutrow

**Comment by joffnerd** [comment]
Sounds like your IP has chnaged and you aren't connected to the Wii

**Comment by Rutrow** [comment]
When I open the trainer it connects OK to my WiiU but I get this error in the trainer error log: 
Error loading json.
Method not found: 'Int32 System.Environment.get_CurrentManagedThreadId()'.   at Newtonsoft.Json.Linq.JsonPath.FieldFilter.<ExecuteFilter>d__4..ctor(Int32 <>1__state)
   at Newtonsoft.Json.Linq.JsonPath.FieldFilter.ExecuteFilter(JToken root, IEnumerable`1 current, Boolean errorWhenNoMatch)
   at Newtonsoft.Json.Linq.JsonPath.JPath.Evaluate(List`1 filters, JToken root, JToken t, Boolean errorWhenNoMatch)
   at Newtonsoft.Json.Linq.JToken.SelectToken(String path, Boolean errorWhenNoMatch)
   at BotwTrainer.MainWindow.MainWindowLoaded(Object sender, RoutedEventArgs e)

When I click on "codes" it opens and the codes work fine but clicking on the "load item" tab
causes a pop-up saying the trainer is unresponsive and it closes down.

**Comment by joffnerd** [comment]
You have unzipped the newtonsoft dll file as well right? Have you checked your .net version?

**Comment by Rutrow** [comment]
I think I have the newest .net version. Which version works best?

**Comment by Rutrow** [comment]
It was the .net version. All working great now. Thank you very much Joffnerd!
