### ISSUE TITLE
Incorrect default value

### ISSUE THREAD

**Issue by skoolzout1** [joffnerd/botw-trainer#83]
The damage multiplier at 439B7A00's default value is 3F800000, or 1.

you have it set to 1.2 as default. you must have been wearing a piece of Attack bonus armour or had an attack potion active when you were looking at it or something lol.

just a minor issue really but i thought id mention it.

Edit: i also just noticed that this value doesnt seem to be Static, and ill have to find a pointer for it

Edit2: here you go, this has worked for me through all the address changes

[0x43AB8C30] + 0x770

**Comment by joffnerd** [comment]
Nice, thanks man. I will amend.
