### ISSUE TITLE
All was well since v3.3 but something has gone horribly wrong. 

### ISSUE THREAD

**Issue by seki777** [joffnerd/botw-trainer#84]
I've been using this program for about a week with no problems. I updated BOTW to 1.1.1 and your program from 3.5 to 3.7.1 and bam all the sudden when I'd connect I'd get a system crash on my Wii U. It's when i'd click load data on 3.5.. than on 3.7.1 it does the same crash right when I hit connect. The wii u shows "Exception type DSI occured!" 

Your program shows

An existing connection was forcibly closed by the remote host.   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at BotwTrainer.TcpConn.Read(Byte[] buffer, UInt32 nobytes, UInt32& bytesRead)
   at BotwTrainer.Gecko.ReadBytes(UInt32 address, UInt32 length)

I updated bully's tcp and tried it, same thing. 

I am making a custom game mode with your program called Breath of Death! so i have a lot of people waiting for a premade save with the alterations from your program. 

I really hope you can help me out! ahaha sorry for being a joke when it comes to the nitty gritty of this.

**Comment by joffnerd** [comment]
Looks like the game update has changed everything so we'll have to re-find all the addresses

**Comment by joffnerd** [comment]
Closing all issues which are probably related to 1.1.1
