### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by xNeptune** [joffnerd/botw-trainer#85]
I've noticed you only possess the coordinates of about 7 or 8 shrines? After the trainer is updated again to match the latest software patch would you like me to put together the coordinates to the shrines that you have not yet added to the list?

**Comment by joffnerd** [comment]
Hey. Yes please, if you have time that would be great. I have just added a few as I've played. Thank you so much

**Comment by xNeptune** [comment]
Currently unable to use the trainer as is due to it not being able to connect properly with the new update, however once the codes are up and working again I'll get right on it, or if I can revert the update I'll get on it sooner
