### ISSUE TITLE
A little help towards your progress.

### ISSUE THREAD

**Issue by L3nggao** [joffnerd/botw-trainer#86]
I'm no expert, but after the update problem, JGecko U still works, I'm hoping perhaps this might help increase your progress speed. 
Both apps aren't running similarly?

**Comment by xNeptune** [comment]
The issue with the trainer is that none of the previous addresses (Cheats) are in the same location therefore none of the cheats on the previous trainer will work with the new update's addresses. Think of it like this, Nintendo put red paint on a piece of paper, with purple and blue following it afterwards, if you closed your eyes you'd know the location of the red, purple and blue paint. But following this update, it's like our eyes were closed and Nintendo switched the order of the colors.

**Comment by L3nggao** [comment]
Oh, I see.
