### ISSUE TITLE
Issues with health code

### ISSUE THREAD

**Issue by Ailuros** [joffnerd/botw-trainer#9]
The health code doesn't work on my US version of the game, at least in the last few versions of the trainer. It worked two or three days ago when I first tested the trainer.

**Comment by Ailuros** [comment]
I can get a RAM dump with JGecko U if you think it will help. I just need to know what region you think I should dump.

**Comment by joffnerd** [comment]
I don't know what address health is for US. IF we can find this out I can amend it for us versions

**Comment by Ailuros** [comment]
Yeah. I can get you a RAM dump if it helps. What's weird is it worked at one point, because a friend of mine (also US) used it to get the Master Sword.

**Comment by Ailuros** [comment]
I don't know what changed. It could be because I'm refreshing before saving now, or it could be something that was changed between 1.9 and 2.0, but the health code works again for my US version.
