### ISSUE TITLE
Amiibo content

### ISSUE THREAD

**Issue by andreomago** [joffnerd/botw-trainer#90]
When can we add amiibos content like Epona and Wolf Link through this app?

**Comment by xNeptune** [comment]
Please don't make repeat posts, your post will be answered as soon as someone with the answer is available to respond. Currently you can already add Epona and Wolf Link through this app if you know what you're doing and know the method to do so. Look around on GBAtemp.net and you should be able to figure out how it's possible but you will be unable to perform the cheat until the new addresses are available, I will personally be getting to work on them in the next few days but I can't this weekend. If you find CosmoCourtney she may be able to help you personally before this trainer receives an update.

**Comment by andreomago** [comment]
Sorry for repeat posta, my PC have a formulary problem. My fault.
--------------------------------------------
Em sex, 31/3/17, xNeptune <notifications@github.com> escreveu:

 Assunto: Re: [joffnerd/botw-trainer] Amiibo content (#90)
 Para: "joffnerd/botw-trainer" <botw-trainer@noreply.github.com>
 Cc: "andreomago" <andre_renato1998@yahoo.com.br>, "Author" <author@noreply.github.com>
 Data: Sexta-feira, 31 de Março de 2017, 21:45
 
 Please don't make repeat posts, your
 post will be answered as soon as someone with the answer is
 available to respond. Currently you can already add Epona
 and Wolf Link through this app if you know what you're doing
 and know the method to do so. Look around on GBAtemp.net and
 you should be able to figure out how it's possible but you
 will be unable to perform the cheat until the new addresses
 are available, I will personally be getting to work on them
 in the next few days but I can't this weekend. If you find
 CosmoCourtney she may be able to help you personally before
 this trainer receives an update.

**Comment by joffnerd** [comment]
No worries, also this is for issues not requests. Thanks
