### ISSUE TITLE
Add "Monster money" next to mon

### ISSUE THREAD

**Issue by demalmar** [joffnerd/botw-trainer#94]
Suggestion/information improvement

I've been spending hours trying to figure out what kind of variable 'Mon' was. Since is a very specific value and not really representative of the whole game, I would suggest to add some extra information next to it, to make it clearer.

**Comment by xNeptune** [comment]
If you haven't encountered the salesman requiring Mon then it's a bit of a safeguard towards spoiling that aspect of the game. Anyone can easily search up what Mon for BOTW is but nobody can erase their memory if mon was given a description in the trainer.

**Comment by joffnerd** [comment]
I will update the labels at some point and add tooltips with more info. Using the trainer is  spoiling the game so i wont hide anything form anyone.

**Comment by demalmar** [comment]
i want to add that some concepts (since the language of the game is not English for me) seem confusing. I see Master Charge there but I have no idea what is that supposed to do. (excuse me if that's my fault).

**Comment by joffnerd** [comment]
I have  added some  tooltips on the codes tab
