### ISSUE TITLE
I get an error on every version now.

### ISSUE THREAD

**Issue by Lowgan** [joffnerd/botw-trainer#95]
I didn't change anything with my console. It worked perfectly yesterday and a before but then all of a sudden it stopped working. I get the same error each time now. .Net is fully updated. I have latest versions of everything. No idea what's up. I don't use loadiine. I have BOTW downloaded through USB loader. I go Mocha CFW-> TCPGecko->BOTW-Jgecko_->BOTW Trainer

Connection closed.   at BotwTrainer.TcpConn.Read(Byte[] buffer, UInt32 nobytes, UInt32& bytesRead)
   at BotwTrainer.Gecko.ReadDataBufferSize()
   at BotwTrainer.Gecko..ctor(TcpConn tcpConn, MainWindow mainWindow)
   at BotwTrainer.MainWindow.ConnectClick(Object sender, RoutedEventArgs e)

**Comment by joffnerd** [comment]
Check your ip address, sounds like it has changed.
