### ISSUE TITLE
Think you can add 2 new codes?

### ISSUE THREAD

**Issue by fefe7198** [joffnerd/botw-trainer#98]
i would like to see a code that makes you have the certain ammount of all materials your holding as well as a Epona Spawning code. (or a code that makes your horse have max stats) can you please add them??

**Comment by xNeptune** [comment]
Epona is already possible but I will see if I can manage to make a pull request that enables you to spawn her much easier. And I'm not sure what you mean by have a certain amount of materials you're holding? The trainer already comes with a materials tab that allows you to edit the quantity of any item within your inventory.

**Comment by fefe7198** [comment]
well what i meant by that is that it takes a while to edit out all my materials so i wanted something that makes me have like 700 of all materials im holding not having to edit each one at a time

**Comment by joffnerd** [comment]
If i get time i might add an update all button or something but since you can do it manually then its not super urgent

**Comment by fefe7198** [comment]
ayyy thx xD
