### ISSUE TITLE
Eventide Island  crashs

### ISSUE THREAD

**Issue by Rootax** [joffnerd/botw-trainer#99]
hello,
First, thx for your hard work, this trainer is flawless for me, hours of using it. Except on Eventide Island. Here, it always random crash. Just a hard freeze, high pitch sound, image of the game frozen. I can happen anywhere and at anytime on this island. I guess it's linked to the inventory "trick" of this island/shrine ?

I'm the only one with this problem ? 3.8.1 trainer here.

**Comment by xNeptune** [comment]
Can you tell me about the events leading up to the crash? Is it something that happens as soon as you enter the island? and I would imagine it's due to the game storing your inventory elsewhere in memory to allow for the trial to be done without any sort of your previous gear being used. I'd suggest not editting anything from the items tab or just disconnect entirely (on the trainer) while doing eventide's trial.

**Comment by Rootax** [comment]
"Can you tell me about the events leading up to the crash?"

Aaaah no, it's really random. I can play 5 min or 20 mins, doing a lot of things, really random (from my point of view). I tried with the trainer disconnected, but same thing. But it's normal I guess since codes were in effect (stamina and items "endurance"). Sorry for my english by the way, it's not my native language.

I'll try without without the endurance codes when I play again, and will report.

**Comment by Rootax** [comment]
I stand corrected. It crashed in the gerudo village to. Hum. The only differences between now and the "crash free" time, is the endurance (weapons shield and bow) codes. I will see what hapen when I don't use them.

**Comment by joffnerd** [comment]
The game has crashed now and then for me as well, I wouldn't say its the trainer though

https://gbatemp.net/threads/frequent-freezes-on-zelda-botw-installed-via-wupinstaller-y-mod.463581/

**Comment by Rootax** [comment]
Nice find. I doubt it's an hardware problem, since I had 0 crash before 1.1.1 .

**Comment by joffnerd** [comment]
Closing as the game crashes aren't trainer specfic
